export class CatalogosACargar {
    public static readonly matricesASincronizar=[
        //persona
        {
            catalogo:"oreja",
            uri:"/v1/catalogos/media-filiacion/oreja"
        },
        {
            catalogo:"labio_ojo",
            uri:'/v1/catalogos/media-filiacion/labio-ojo'
        },
        {
            catalogo:"frente_menton",
            uri:'/v1/catalogos/media-filiacion/frente-menton'

        },
        {
            catalogo:"complexion_piel_sangre",
            uri:'/v1/catalogos/media-filiacion/complexion-piel-sangre'
        },
        {
            catalogo:"ceja_boca",
            uri:'/v1/catalogos/media-filiacion/ceja-boca'

        },
        {
            catalogo:"cara_nariz",
            uri:'/v1/catalogos/media-filiacion/cara-nariz'

        },
        {
            catalogo:"cabello",
            uri:'/v1/catalogos/media-filiacion/cabello'

        },
        {
            catalogo:"nacionalidad_religion",
            uri:'/v1/catalogos/nacionalidad-religion'

        },
        {
            catalogo:"tipo_detenido",
            uri:'/v1/catalogos/persona/tipo-detenido'

        },
        {
            catalogo:"idioma_identificacion",
            uri:'/v1/catalogos/persona/idioma'

        },
        //armas
        {
            catalogo:"clase_arma",
            uri:'/v1/catalogos/arma/clase-arma' 

        },
        {
            catalogo:"calibre_mecanismo",
            uri:'/v1/catalogos/arma/calibre-mecanismo'    
        },
        //lugares
        {
            catalogo:"detalle_lugar", 
            uri:'/v1/catalogos/lugar/detalle-lugar'
        },
        //vehiculos
        {
            catalogo:"tipo_uso_tipo_vehiculo",
            uri:'/v1/catalogos/vehiculo/tipo-uso-vehiculo'

        },
        {
            catalogo:"procedencia_aseguradora",
            uri:'/v1/catalogos/vehiculo/procedencia-aseguradora'

        },
        {
            catalogo:"motivo_color_clase",
            uri:'/v1/catalogos/vehiculo/motivo-color-clase'

        },
        {
            catalogo:"marca_submarca",
            uri:'/v1/catalogos/vehiculo/marca-submarca'


        },
        //relacion
        {
            catalogo:"modalidad_ambito",
            uri:'/v1/catalogos/relacion/modalidad-ambito'
        },
        {
            catalogo:"violencia_genero",
            uri:'/v1/catalogos/relacion/violencia-genero'
        },
        {
            catalogo:"tipo_transportacion",
            uri:'/v1/catalogos/relacion/tipo-transportacion'
        },
        {
            catalogo:"efecto_detalle",
            uri:'/v1/catalogos/relacion/efecto-detalle'
        },
        {
            catalogo:"desaparicion_consumacion",
            uri:'/v1/catalogos/relacion/desaparicion-consumacion'
        },
        {
            catalogo:"conducta_detalle",
            uri:'/v1/catalogos/relacion/conducta-detalle'
        },


    ];

    public static readonly catalogosASincronizar=[
        //persona
        {
            catalogo:"delito",
            uri:"/v1/catalogos/delitos"
        },
        {
            catalogo:"modalidad_delito",
            uri:'/v1/catalogos/relacion/modalidad-delito/options'
        },
        {
            catalogo:"concurso_delito",
            uri:'/v1/catalogos/relacion/concurso-delito/options'
        },
        {
            catalogo:"grado_participacion",
            uri:'/v1/catalogos/relacion/grado-participacion/options'
        },
        {
            catalogo:"forma_comision",
            uri:'/v1/catalogos/relacion/forma-comision/options'
        },
        {
            catalogo:"clasificiacion_delito_orden",
            uri:'/v1/catalogos/relacion/clasificacion-delito-orden/options'
        },
        {
            catalogo:"forma_accion",
            uri:'/v1/catalogos/relacion/forma-accion/options'
        },
        {
            catalogo:"elemento_comision",
            uri:'/v1/catalogos/relacion/elemento-comision/options'
        },
        {
            catalogo:"forma_conducta",
            uri:'/v1/catalogos/relacion/forma-conducta/options'
        },
        {
            catalogo:"sexo",
            uri:'/v1/catalogos/persona/sexo/options'
        },
        {
            catalogo:"escolaridad",
            uri:'/v1/catalogos/persona/escolaridad/options'
        },
        {
            catalogo:"ocupacion", 
            uri:'/v1/catalogos/persona/ocupacion/options'
        },
        {
            catalogo:"estado_civil",
            uri:'/v1/catalogos/persona/estado-civil/options'
        },
        {
            catalogo:"grupo_etnico",
            uri:'/v1/catalogos/persona/grupo-etnico/options'
        },
        {
            catalogo:"alfabetismo",
            uri:'/v1/catalogos/persona/alfabetismo/options'
        },
        {
            catalogo:"interprete",
            uri:'/v1/catalogos/persona/interprete/options'
        },
        {
            catalogo:"pais",
            uri:'/v1/catalogos/pais/options'
        },
        {
            catalogo:"estado",
            uri:'/v1/catalogos/estado'
        },
        {
            catalogo:"municipio",
            uri:'/v1/catalogos/municipio'
        },
        {
            catalogo:"distrito",
            uri:'/v1/catalogos/usuario/distrito/options'
        },
        {
            catalogo:"clasificacion_delito",
            uri:'/v1/catalogos/relacion/clasificacion-delito/options'
        },
        {
            catalogo:"clasificacion_delito_orden",
            uri:'/v1/catalogos/relacion/clasificacion-delito-orden/options'
        },
        {
            catalogo:"tipo_interviniente",
            uri:'/v1/base/tipos-intervinientes/options'
        },
        {
            catalogo:"victima_querellante",
            uri:'/v1/catalogos/solicitud-preliminar/victima-querellante/options'
        },
        {
            catalogo:"denuncia_querellante",
            uri:'/v1/catalogos/solicitud-preliminar/denuncia-querella/options'
        },
        {
            catalogo:"perito_materia",
            uri:'/v1/catalogos/solicitud-preliminar/perito-materia/options'
        },
        {
            catalogo:"tipo_examen",
            uri:'/v1/catalogos/solicitud-preliminar/denuncia-querella/options'
        },
        {
            catalogo:"idioma",
            uri:'/v1/catalogos/persona/idioma/options'
        },
        {
            catalogo:"adiccion",
            uri:'/v1/catalogos/persona/adiccion/options'
        },
        {
            catalogo:"nacionalidad",
            uri:'/v1/catalogos/persona/nacionalidad/options'
        },
        {
            catalogo:"tipo_domicilio",
            uri:'/v1/catalogos/tipo-domicilio/options'
        },
        {
            catalogo:"tipo_persona",
            uri:'/v1/catalogos/predenuncia/tipo-persona/options'
        }
    ];
}
