import { FormBuilder } from '@angular/forms';

export class Form {
    public static createForm(_fbuilder: FormBuilder) {
        return _fbuilder.group({
            numeroReferencia: [null],
            primerResponsable: [null],
            institucion: [null],
            municipio: [null],
            cuip: [null],
            // 2
            enteroHecho: [null],
            especifique: [null],
            fechaConocimiento: [null],
            horaConocimiento: [null],
            // 3
            fechaArribo: [null],
            horaArribo: [null],
            entidadArribo: [null],
            municipioArribo: [null],
            localidadArribo: [null],
            calleArribo: [null],
            numExtArribo: [null],
            entreCalleArribo: [null],
            tramoCarreteroArribo: [null],
            tipoArribo: [null],
            kmArribo: [null],
            latitudArribo: [null],
            longitudArribo: [null],
            riesgoPara: [null],
            tipoRiesgo: [null],
            especifiqueRiesgo: [null],
            apoyo: [null],
            numEconomico: [null],
            especifiqueApoyo: [null],
            narracionHechos: [null],
            // 4
            fechaPreservacion: [null],
            horaPreservacion: [null],
            acordonamiento: [null],
            cuipAcordonamiento: [null],
            paternoAcordonamiento: [null],
            maternoAcordonamiento: [null],
            nombreAcordonamiento: [null],
            resguardo: [null],
            cuipResguardo: [null],
            paternoResguardo: [null],
            maternoResguardo: [null],
            nombreResguardo: [null],
            // 5
            fechaCertificado: [null],
            horaCertificado: [null],
            medico: [null],
            medicoAgencia: [null],
            nombreAgencia: [null],
            municipioAgencia: [null],
            numAgencia: [null],
            medicoParticular: [null],
            municipioParticular: [null],
            calleParticular: [null],
            paternoParticular: [null],
            maternoParticular: [null],
            nombreParticular: [null],
            adscripcionParticular: [null],
            // Anexo 1
            detenido: [null],
            comprendioDerechos: [null],
            cuipDetenido: [null],
            paternoDetenido: [null],
            maternoDetenido: [null],
            nombreDetenido: [null],
            adscripcionDetenido: [null],
            // Anexo 2
            motivoDetencion: [null],
            fechaDetencion: [null],
            horaDetencion: [null],
            // Anexo 3
            situacionUsoFuerza: [null],
            asistenciaMedica: [null],
            nivelUsoFuerza: [null],
            detenidoFuerza: [null],  
            maternoFuerza: [null],
            nombreFuerza: [null],
            primerResponsableFuerza: [null],  
            maternoPrimerFuerza: [null],
            nombrePrimerFuerza: [null],
            trasladoCanalizacion: [null],
            fechaCanalizacion: [null],
            horaCanalizacion: [null],
            // Anexo 5
            detenidoPertenencia: [null],
            objeto: [null],
            cantidadObjeto: [null],
            // Anexo 6
            paternoVictima: [null],  
            maternoVictima: [null],
            nombreVictimam: [null],
            cuipVictima: [null],  
            paternoPrimerVictima: [null],
            maternoPrimerVictima: [null],
            nombrePrimerVictima: [null],
            adscripcionPrimerVictima: [null],
            // Anexo 7
            trasladoA: [null],  
            tipoTraslado: [null],
            especifiqueTraslado: [null],
            agenciaTraslado: [null],  
            estadoAgenciaTraslado: [null],
            municipioAgenciaTraslado: [null],
            coloniaAgenciaTraslado: [null],
            calleAgenciaTraslado: [null],
            numExtAgenciaTraslado: [null],
            cpAgenciaTraslado: [null],
            personaTraslado: [null],  
            estadoPersonaTraslado: [null],
            municipioPersonaTraslado: [null],
            coloniaPersonaTraslado: [null],
            callePersonaTraslado: [null],
            numExtPersonaTraslado: [null],
            cuipEntregaTraslado: [null],  
            paternoEntregaTraslado: [null],
            meternoEntregaTraslado: [null],
            nombreEntregaTraslado: [null],
            cargaEntregaTraslado: [null],
            paternoRecibeTraslado: [null],
            meternoRecibeTraslado: [null],
            nombreRecibeTraslado: [null],
            cargaRecibeTraslado: [null],
            fechaTraslado: [null],
            horaTraslado: [null],
        })
    }
}