import { FormBuilder } from '@angular/forms';

export class Form {
    public static createForm(_fbuilder: FormBuilder) {
        return _fbuilder.group({
            numeroReferencia: [''],
            primerResponsable: [''],
            institucion: [''],
            municipio: [''],
            cuip: [''],
            // 2
            enteroHecho: [''],
            especifique: [''],
            fechaConocimiento: [''],
            horaConocimiento: [''],
            // 3
            fechaArribo: [''],
            horaArribo: [''],
            entidadArribo: [''],
            municipioArribo: [''],
            localidadArribo: [''],
            calleArribo: [''],
            numIntArribo: [''],
            numExtArribo: [''],
            entreCalleArribo: [''],
            tramoCarreteroArribo: [''],
            tipoArribo: [''],
            kmArribo: [''],
            latitudArribo: [''],
            longitudArribo: [''],
            riesgoPara: [''],
            tipoRiesgo: [''],
            especifiqueRiesgo: [''],
            apoyo: [''],
            numEconomico: [''],
            especifiqueApoyo: [''],
            narracionHechos: [''],
            //radios
            proteccion: [''],
            recepcionAcciones: [''],
            recoleccionAcciones: [''],
            proteccionAcciones: [''],
            resguardoAcciones: [''],
            preservacionAcciones: [''],
            informarAcciones: [''],
            proteccionAccionesA: [''],
            resguardoAccionesA: [''],
            detencionAcciones: [''],
            fuerzaAcciones: [''],
            puestoAcciones: [''],
            inventarioAcciones: [''],
            trasladoAcciones: [''],
            inspeccionesAcciones: [''],
            echosFavorAcciones:[''],
            trasladoAccionesA:[''],
            trasladoAccionesDe:[''],
            inspeccionesAccionesA:[''],
            entrevistasAcciones:[''],
            // 4
            fechaPreservacion: [''],
            horaPreservacion: [''],
            acordonamiento: [''],
            cuipAcordonamiento: [''],
            paternoAcordonamiento: [''],
            maternoAcordonamiento: [''],
            nombreAcordonamiento: [''],
            adcripcionAcordonamiento: [''],
            resguardo: [''],
            cuipResguardo: [''],
            paternoResguardo: [''],
            maternoResguardo: [''],
            nombreResguardo: [''],
            adcripcionResguardo: [''],
            // 5
            fechaCertificado: [''],
            horaCertificado: [''],
            medico: [''],
            medicoAgencia: [''],
            nombreAgencia: [''],
            municipioAgencia: [''],
            calleAgencia: [''],
            numAgencia: [''],
            medicoParticular: [''],
            municipioParticular: [''],
            calleParticular: [''],
            numParticular: [''],
            cuipParticular: [''],
            paternoParticular: [''],
            maternoParticular: [''],
            nombreParticular: [''],
            adscripcionParticular: [''],
            // Anexo 1
            detenido: [''],
            comprendioDerechos: [''],
            cuipDetenido: [''],
            paternoDetenido: [''],
            maternoDetenido: [''],
            nombreDetenido: [''],
            adscripcionDetenido: [''],
            // Anexo 2
            motivoDetencion: [''],
            fechaDetencion: [''],
            horaDetencion: [''],
            entidadDetencion: [''],
            municipioDetencion: [''],
            localidadDetencion: [''],
            calleDetencion: [''],
            numIntDetencion: [''],
            numExtDetencion: [''],
            entreCalleDetencion: [''],
            cpDetencion: [''],
            latitudDetencion: [''],
            longitudDetencion: [''],
            paternoDetecion: [''],
            maternoDetecion: [''],
            nombreDetencion: [''],
            sexoDetencion: [''],
            edadRefeDetencion: [''],
            calleDetenido: [''],
            numExtDetenido: [''],
            numIntDetenido: [''],
            cpDetenido: [''],
            fechaDetenido: [''],
            casadoDetenido: [''],
            ocupacionDetenido: [''],
            nacionalidadDetenido: [''],
            rfcCurpDetenido: [''],
            lecturaDerechosDetenido: [''],
            señalesParticularesDetenido: [''],
            descripcionFisicaDetenido: [''],
            tipoVestimentaDetenido: [''],
            pertenenciasDetenido: [''],

            // Anexo 3
            situacionUsoFuerza: [''],
            asistenciaMedica: [''],
            nivelUsoFuerza: [''],
            detenidoFuerza: [''],
            paternoFuerza: [''],  
            maternoFuerza: [''],
            nombreFuerza: [''],
            primerResponsableFuerza: [''],  
            paternoPrimerFuerza: [''],
            maternoPrimerFuerza: [''],
            nombrePrimerFuerza: [''],   
            trasladoCanalizacion: [''],
            fechaCanalizacion: [''],
            horaCanalizacion: [''],
            // Anexo 5
            detenidoPertenencia: [''],
            objeto: [''],
            cantidadObjeto: [''],
            // Anexo 6
            paternoVictima: [''],  
            maternoVictima: [''],
            nombreVictimam: [''],
            cuipVictima: [''],  
            paternoPrimerVictima: [''],
            maternoPrimerVictima: [''],
            nombrePrimerVictima: [''],
            adscripcionPrimerVictima: [''],
            // Anexo 7
            trasladoA: [''],  
            tipoTraslado: [''],
            especifiqueTraslado: [''],
            agenciaTraslado: [''],  
            estadoAgenciaTraslado: [''],
            municipioAgenciaTraslado: [''],
            coloniaAgenciaTraslado: [''],
            calleAgenciaTraslado: [''],
            numExtAgenciaTraslado: [''],
            cpAgenciaTraslado: [''],
            personaTraslado: [''],  
            estadoPersonaTraslado: [''],
            municipioPersonaTraslado: [''],
            coloniaPersonaTraslado: [''],
            callePersonaTraslado: [''],
            numExtPersonaTraslado: [''],
            cuipEntregaTraslado: [''],  
            paternoEntregaTraslado: [''],
            meternoEntregaTraslado: [''],
            nombreEntregaTraslado: [''],
            cargaEntregaTraslado: [''],
            paternoRecibeTraslado: [''],
            meternoRecibeTraslado: [''],
            nombreRecibeTraslado: [''],
            cargaRecibeTraslado: [''],
            fechaTraslado: [''],
            horaTraslado: [''],
        })
    }
}