export class arrCABELLO {
    public static readonly arreglo = [
        {id:1,cantidad:'POCO',color:'AZUL',forma:'Recta',calvicie:'chica',implantacion:'chica',},
        {id:2,cantidad:'POCO',color:'AZUL',forma:'Recta',calvicie:'chica',implantacion:'mediana',},
        {id:3,cantidad:'POCO',color:'AZUL',forma:'Recta',calvicie:'chica',implantacion:'grande',},
        {id:4,cantidad:'POCO',color:'AZUL',forma:'Recta',calvicie:'mediana',implantacion:'chica',},
        {id:5,cantidad:'POCO',color:'AZUL',forma:'Recta',calvicie:'mediana',implantacion:'mediana',},
        {id:6,cantidad:'POCO',color:'AZUL',forma:'Recta',calvicie:'mediana',implantacion:'grande',},
        {id:7,cantidad:'POCO',color:'AZUL',forma:'Recta',calvicie:'grande',implantacion:'chica',},
        {id:8,cantidad:'POCO',color:'AZUL',forma:'Recta',calvicie:'grande',implantacion:'mediana',},
        {id:9,cantidad:'POCO',color:'AZUL',forma:'Recta',calvicie:'grande',implantacion:'grande',},
        {id:10,cantidad:'POCO',color:'AZUL',forma:'S',calvicie:'chica',implantacion:'chica',},
        {id:11,cantidad:'POCO',color:'AZUL',forma:'S',calvicie:'chica',implantacion:'mediana',},
        {id:12,cantidad:'POCO',color:'AZUL',forma:'S',calvicie:'chica',implantacion:'grande',},
        {id:13,cantidad:'POCO',color:'AZUL',forma:'S',calvicie:'mediana',implantacion:'chica',},
        {id:14,cantidad:'POCO',color:'AZUL',forma:'S',calvicie:'mediana',implantacion:'mediana',},
        {id:15,cantidad:'POCO',color:'AZUL',forma:'S',calvicie:'mediana',implantacion:'grande',},
        {id:16,cantidad:'POCO',color:'AZUL',forma:'S',calvicie:'grande',implantacion:'chica',},
        {id:17,cantidad:'POCO',color:'AZUL',forma:'S',calvicie:'grande',implantacion:'mediana',},
        {id:18,cantidad:'POCO',color:'AZUL',forma:'S',calvicie:'grande',implantacion:'grande',},
        {id:19,cantidad:'POCO',color:'AZUL',forma:'U',calvicie:'chica',implantacion:'chica',},
        {id:20,cantidad:'POCO',color:'AZUL',forma:'U',calvicie:'chica',implantacion:'mediana',},
        {id:21,cantidad:'POCO',color:'AZUL',forma:'U',calvicie:'chica',implantacion:'grande',},
        {id:22,cantidad:'POCO',color:'AZUL',forma:'U',calvicie:'mediana',implantacion:'chica',},
        {id:23,cantidad:'POCO',color:'AZUL',forma:'U',calvicie:'mediana',implantacion:'mediana',},
        {id:24,cantidad:'POCO',color:'AZUL',forma:'U',calvicie:'mediana',implantacion:'grande',},
        {id:25,cantidad:'POCO',color:'AZUL',forma:'U',calvicie:'grande',implantacion:'chica',},
        {id:26,cantidad:'POCO',color:'AZUL',forma:'U',calvicie:'grande',implantacion:'mediana',},
        {id:27,cantidad:'POCO',color:'AZUL',forma:'U',calvicie:'grande',implantacion:'grande',},
        {id:28,cantidad:'POCO',color:'AZUL',forma:'U invertida',calvicie:'chica',implantacion:'chica',},
        {id:29,cantidad:'POCO',color:'AZUL',forma:'U invertida',calvicie:'chica',implantacion:'mediana',},
        {id:30,cantidad:'POCO',color:'AZUL',forma:'U invertida',calvicie:'chica',implantacion:'grande',},
        {id:31,cantidad:'POCO',color:'AZUL',forma:'U invertida',calvicie:'mediana',implantacion:'chica',},
        {id:32,cantidad:'POCO',color:'AZUL',forma:'U invertida',calvicie:'mediana',implantacion:'mediana',},
        {id:33,cantidad:'POCO',color:'AZUL',forma:'U invertida',calvicie:'mediana',implantacion:'grande',},
        {id:34,cantidad:'POCO',color:'AZUL',forma:'U invertida',calvicie:'grande',implantacion:'chica',},
        {id:35,cantidad:'POCO',color:'AZUL',forma:'U invertida',calvicie:'grande',implantacion:'mediana',},
        {id:36,cantidad:'POCO',color:'AZUL',forma:'U invertida',calvicie:'grande',implantacion:'grande',},
        {id:37,cantidad:'POCO',color:'AZUL',forma:'Rapada',calvicie:'chica',implantacion:'chica',},
        {id:38,cantidad:'POCO',color:'AZUL',forma:'Rapada',calvicie:'chica',implantacion:'mediana',},
        {id:39,cantidad:'POCO',color:'AZUL',forma:'Rapada',calvicie:'chica',implantacion:'grande',},
        {id:40,cantidad:'POCO',color:'AZUL',forma:'Rapada',calvicie:'mediana',implantacion:'chica',},
        {id:41,cantidad:'POCO',color:'AZUL',forma:'Rapada',calvicie:'mediana',implantacion:'mediana',},
        {id:42,cantidad:'POCO',color:'AZUL',forma:'Rapada',calvicie:'mediana',implantacion:'grande',},
        {id:43,cantidad:'POCO',color:'AZUL',forma:'Rapada',calvicie:'grande',implantacion:'chica',},
        {id:44,cantidad:'POCO',color:'AZUL',forma:'Rapada',calvicie:'grande',implantacion:'mediana',},
        {id:45,cantidad:'POCO',color:'AZUL',forma:'Rapada',calvicie:'grande',implantacion:'grande',},
        {id:46,cantidad:'POCO',color:'NEGRO',forma:'Recta',calvicie:'chica',implantacion:'chica',},
        {id:47,cantidad:'POCO',color:'NEGRO',forma:'Recta',calvicie:'chica',implantacion:'mediana',},
        {id:48,cantidad:'POCO',color:'NEGRO',forma:'Recta',calvicie:'chica',implantacion:'grande',},
        {id:49,cantidad:'POCO',color:'NEGRO',forma:'Recta',calvicie:'mediana',implantacion:'chica',},
        {id:50,cantidad:'POCO',color:'NEGRO',forma:'Recta',calvicie:'mediana',implantacion:'mediana',},
        {id:51,cantidad:'POCO',color:'NEGRO',forma:'Recta',calvicie:'mediana',implantacion:'grande',},
        {id:52,cantidad:'POCO',color:'NEGRO',forma:'Recta',calvicie:'grande',implantacion:'chica',},
        {id:53,cantidad:'POCO',color:'NEGRO',forma:'Recta',calvicie:'grande',implantacion:'mediana',},
        {id:54,cantidad:'POCO',color:'NEGRO',forma:'Recta',calvicie:'grande',implantacion:'grande',},
        {id:55,cantidad:'POCO',color:'NEGRO',forma:'S',calvicie:'chica',implantacion:'chica',},
        {id:56,cantidad:'POCO',color:'NEGRO',forma:'S',calvicie:'chica',implantacion:'mediana',},
        {id:57,cantidad:'POCO',color:'NEGRO',forma:'S',calvicie:'chica',implantacion:'grande',},
        {id:58,cantidad:'POCO',color:'NEGRO',forma:'S',calvicie:'mediana',implantacion:'chica',},
        {id:59,cantidad:'POCO',color:'NEGRO',forma:'S',calvicie:'mediana',implantacion:'mediana',},
        {id:60,cantidad:'POCO',color:'NEGRO',forma:'S',calvicie:'mediana',implantacion:'grande',},
        {id:61,cantidad:'POCO',color:'NEGRO',forma:'S',calvicie:'grande',implantacion:'chica',},
        {id:62,cantidad:'POCO',color:'NEGRO',forma:'S',calvicie:'grande',implantacion:'mediana',},
        {id:63,cantidad:'POCO',color:'NEGRO',forma:'S',calvicie:'grande',implantacion:'grande',},
        {id:64,cantidad:'POCO',color:'NEGRO',forma:'U',calvicie:'chica',implantacion:'chica',},
        {id:65,cantidad:'POCO',color:'NEGRO',forma:'U',calvicie:'chica',implantacion:'mediana',},
        {id:66,cantidad:'POCO',color:'NEGRO',forma:'U',calvicie:'chica',implantacion:'grande',},
        {id:67,cantidad:'POCO',color:'NEGRO',forma:'U',calvicie:'mediana',implantacion:'chica',},
        {id:68,cantidad:'POCO',color:'NEGRO',forma:'U',calvicie:'mediana',implantacion:'mediana',},
        {id:69,cantidad:'POCO',color:'NEGRO',forma:'U',calvicie:'mediana',implantacion:'grande',},
        {id:70,cantidad:'POCO',color:'NEGRO',forma:'U',calvicie:'grande',implantacion:'chica',},
        {id:71,cantidad:'POCO',color:'NEGRO',forma:'U',calvicie:'grande',implantacion:'mediana',},
        {id:72,cantidad:'POCO',color:'NEGRO',forma:'U',calvicie:'grande',implantacion:'grande',},
        {id:73,cantidad:'POCO',color:'NEGRO',forma:'U invertida',calvicie:'chica',implantacion:'chica',},
        {id:74,cantidad:'POCO',color:'NEGRO',forma:'U invertida',calvicie:'chica',implantacion:'mediana',},
        {id:75,cantidad:'POCO',color:'NEGRO',forma:'U invertida',calvicie:'chica',implantacion:'grande',},
        {id:76,cantidad:'POCO',color:'NEGRO',forma:'U invertida',calvicie:'mediana',implantacion:'chica',},
        {id:77,cantidad:'POCO',color:'NEGRO',forma:'U invertida',calvicie:'mediana',implantacion:'mediana',},
        {id:78,cantidad:'POCO',color:'NEGRO',forma:'U invertida',calvicie:'mediana',implantacion:'grande',},
        {id:79,cantidad:'POCO',color:'NEGRO',forma:'U invertida',calvicie:'grande',implantacion:'chica',},
        {id:80,cantidad:'POCO',color:'NEGRO',forma:'U invertida',calvicie:'grande',implantacion:'mediana',},
        {id:81,cantidad:'POCO',color:'NEGRO',forma:'U invertida',calvicie:'grande',implantacion:'grande',},
        {id:82,cantidad:'POCO',color:'NEGRO',forma:'Rapada',calvicie:'chica',implantacion:'chica',},
        {id:83,cantidad:'POCO',color:'NEGRO',forma:'Rapada',calvicie:'chica',implantacion:'mediana',},
        {id:84,cantidad:'POCO',color:'NEGRO',forma:'Rapada',calvicie:'chica',implantacion:'grande',},
        {id:85,cantidad:'POCO',color:'NEGRO',forma:'Rapada',calvicie:'mediana',implantacion:'chica',},
        {id:86,cantidad:'POCO',color:'NEGRO',forma:'Rapada',calvicie:'mediana',implantacion:'mediana',},
        {id:87,cantidad:'POCO',color:'NEGRO',forma:'Rapada',calvicie:'mediana',implantacion:'grande',},
        {id:88,cantidad:'POCO',color:'NEGRO',forma:'Rapada',calvicie:'grande',implantacion:'chica',},
        {id:89,cantidad:'POCO',color:'NEGRO',forma:'Rapada',calvicie:'grande',implantacion:'mediana',},
        {id:90,cantidad:'POCO',color:'NEGRO',forma:'Rapada',calvicie:'grande',implantacion:'grande',},
        {id:91,cantidad:'POCO',color:'CAFE',forma:'Recta',calvicie:'chica',implantacion:'chica',},
        {id:92,cantidad:'POCO',color:'CAFE',forma:'Recta',calvicie:'chica',implantacion:'mediana',},
        {id:93,cantidad:'POCO',color:'CAFE',forma:'Recta',calvicie:'chica',implantacion:'grande',},
        {id:94,cantidad:'POCO',color:'CAFE',forma:'Recta',calvicie:'mediana',implantacion:'chica',},
        {id:95,cantidad:'POCO',color:'CAFE',forma:'Recta',calvicie:'mediana',implantacion:'mediana',},
        {id:96,cantidad:'POCO',color:'CAFE',forma:'Recta',calvicie:'mediana',implantacion:'grande',},
        {id:97,cantidad:'POCO',color:'CAFE',forma:'Recta',calvicie:'grande',implantacion:'chica',},
        {id:98,cantidad:'POCO',color:'CAFE',forma:'Recta',calvicie:'grande',implantacion:'mediana',},
        {id:99,cantidad:'POCO',color:'CAFE',forma:'Recta',calvicie:'grande',implantacion:'grande',},
        {id:100,cantidad:'POCO',color:'CAFE',forma:'S',calvicie:'chica',implantacion:'chica',},
        {id:101,cantidad:'POCO',color:'CAFE',forma:'S',calvicie:'chica',implantacion:'mediana',},
        {id:102,cantidad:'POCO',color:'CAFE',forma:'S',calvicie:'chica',implantacion:'grande',},
        {id:103,cantidad:'POCO',color:'CAFE',forma:'S',calvicie:'mediana',implantacion:'chica',},
        {id:104,cantidad:'POCO',color:'CAFE',forma:'S',calvicie:'mediana',implantacion:'mediana',},
        {id:105,cantidad:'POCO',color:'CAFE',forma:'S',calvicie:'mediana',implantacion:'grande',},
        {id:106,cantidad:'POCO',color:'CAFE',forma:'S',calvicie:'grande',implantacion:'chica',},
        {id:107,cantidad:'POCO',color:'CAFE',forma:'S',calvicie:'grande',implantacion:'mediana',},
        {id:108,cantidad:'POCO',color:'CAFE',forma:'S',calvicie:'grande',implantacion:'grande',},
        {id:109,cantidad:'POCO',color:'CAFE',forma:'U',calvicie:'chica',implantacion:'chica',},
        {id:110,cantidad:'POCO',color:'CAFE',forma:'U',calvicie:'chica',implantacion:'mediana',},
        {id:111,cantidad:'POCO',color:'CAFE',forma:'U',calvicie:'chica',implantacion:'grande',},
        {id:112,cantidad:'POCO',color:'CAFE',forma:'U',calvicie:'mediana',implantacion:'chica',},
        {id:113,cantidad:'POCO',color:'CAFE',forma:'U',calvicie:'mediana',implantacion:'mediana',},
        {id:114,cantidad:'POCO',color:'CAFE',forma:'U',calvicie:'mediana',implantacion:'grande',},
        {id:115,cantidad:'POCO',color:'CAFE',forma:'U',calvicie:'grande',implantacion:'chica',},
        {id:116,cantidad:'POCO',color:'CAFE',forma:'U',calvicie:'grande',implantacion:'mediana',},
        {id:117,cantidad:'POCO',color:'CAFE',forma:'U',calvicie:'grande',implantacion:'grande',},
        {id:118,cantidad:'POCO',color:'CAFE',forma:'U invertida',calvicie:'chica',implantacion:'chica',},
        {id:119,cantidad:'POCO',color:'CAFE',forma:'U invertida',calvicie:'chica',implantacion:'mediana',},
        {id:120,cantidad:'POCO',color:'CAFE',forma:'U invertida',calvicie:'chica',implantacion:'grande',},
        {id:121,cantidad:'POCO',color:'CAFE',forma:'U invertida',calvicie:'mediana',implantacion:'chica',},
        {id:122,cantidad:'POCO',color:'CAFE',forma:'U invertida',calvicie:'mediana',implantacion:'mediana',},
        {id:123,cantidad:'POCO',color:'CAFE',forma:'U invertida',calvicie:'mediana',implantacion:'grande',},
        {id:124,cantidad:'POCO',color:'CAFE',forma:'U invertida',calvicie:'grande',implantacion:'chica',},
        {id:125,cantidad:'POCO',color:'CAFE',forma:'U invertida',calvicie:'grande',implantacion:'mediana',},
        {id:126,cantidad:'POCO',color:'CAFE',forma:'U invertida',calvicie:'grande',implantacion:'grande',},
        {id:127,cantidad:'POCO',color:'CAFE',forma:'Rapada',calvicie:'chica',implantacion:'chica',},
        {id:128,cantidad:'POCO',color:'CAFE',forma:'Rapada',calvicie:'chica',implantacion:'mediana',},
        {id:129,cantidad:'POCO',color:'CAFE',forma:'Rapada',calvicie:'chica',implantacion:'grande',},
        {id:130,cantidad:'POCO',color:'CAFE',forma:'Rapada',calvicie:'mediana',implantacion:'chica',},
        {id:131,cantidad:'POCO',color:'CAFE',forma:'Rapada',calvicie:'mediana',implantacion:'mediana',},
        {id:132,cantidad:'POCO',color:'CAFE',forma:'Rapada',calvicie:'mediana',implantacion:'grande',},
        {id:133,cantidad:'POCO',color:'CAFE',forma:'Rapada',calvicie:'grande',implantacion:'chica',},
        {id:134,cantidad:'POCO',color:'CAFE',forma:'Rapada',calvicie:'grande',implantacion:'mediana',},
        {id:135,cantidad:'POCO',color:'CAFE',forma:'Rapada',calvicie:'grande',implantacion:'grande',},
        {id:136,cantidad:'POCO',color:'ROJO',forma:'Recta',calvicie:'chica',implantacion:'chica',},
        {id:137,cantidad:'POCO',color:'ROJO',forma:'Recta',calvicie:'chica',implantacion:'mediana',},
        {id:138,cantidad:'POCO',color:'ROJO',forma:'Recta',calvicie:'chica',implantacion:'grande',},
        {id:139,cantidad:'POCO',color:'ROJO',forma:'Recta',calvicie:'mediana',implantacion:'chica',},
        {id:140,cantidad:'POCO',color:'ROJO',forma:'Recta',calvicie:'mediana',implantacion:'mediana',},
        {id:141,cantidad:'POCO',color:'ROJO',forma:'Recta',calvicie:'mediana',implantacion:'grande',},
        {id:142,cantidad:'POCO',color:'ROJO',forma:'Recta',calvicie:'grande',implantacion:'chica',},
        {id:143,cantidad:'POCO',color:'ROJO',forma:'Recta',calvicie:'grande',implantacion:'mediana',},
        {id:144,cantidad:'POCO',color:'ROJO',forma:'Recta',calvicie:'grande',implantacion:'grande',},
        {id:145,cantidad:'POCO',color:'ROJO',forma:'S',calvicie:'chica',implantacion:'chica',},
        {id:146,cantidad:'POCO',color:'ROJO',forma:'S',calvicie:'chica',implantacion:'mediana',},
        {id:147,cantidad:'POCO',color:'ROJO',forma:'S',calvicie:'chica',implantacion:'grande',},
        {id:148,cantidad:'POCO',color:'ROJO',forma:'S',calvicie:'mediana',implantacion:'chica',},
        {id:149,cantidad:'POCO',color:'ROJO',forma:'S',calvicie:'mediana',implantacion:'mediana',},
        {id:150,cantidad:'POCO',color:'ROJO',forma:'S',calvicie:'mediana',implantacion:'grande',},
        {id:151,cantidad:'POCO',color:'ROJO',forma:'S',calvicie:'grande',implantacion:'chica',},
        {id:152,cantidad:'POCO',color:'ROJO',forma:'S',calvicie:'grande',implantacion:'mediana',},
        {id:153,cantidad:'POCO',color:'ROJO',forma:'S',calvicie:'grande',implantacion:'grande',},
        {id:154,cantidad:'POCO',color:'ROJO',forma:'U',calvicie:'chica',implantacion:'chica',},
        {id:155,cantidad:'POCO',color:'ROJO',forma:'U',calvicie:'chica',implantacion:'mediana',},
        {id:156,cantidad:'POCO',color:'ROJO',forma:'U',calvicie:'chica',implantacion:'grande',},
        {id:157,cantidad:'POCO',color:'ROJO',forma:'U',calvicie:'mediana',implantacion:'chica',},
        {id:158,cantidad:'POCO',color:'ROJO',forma:'U',calvicie:'mediana',implantacion:'mediana',},
        {id:159,cantidad:'POCO',color:'ROJO',forma:'U',calvicie:'mediana',implantacion:'grande',},
        {id:160,cantidad:'POCO',color:'ROJO',forma:'U',calvicie:'grande',implantacion:'chica',},
        {id:161,cantidad:'POCO',color:'ROJO',forma:'U',calvicie:'grande',implantacion:'mediana',},
        {id:162,cantidad:'POCO',color:'ROJO',forma:'U',calvicie:'grande',implantacion:'grande',},
        {id:163,cantidad:'POCO',color:'ROJO',forma:'U invertida',calvicie:'chica',implantacion:'chica',},
        {id:164,cantidad:'POCO',color:'ROJO',forma:'U invertida',calvicie:'chica',implantacion:'mediana',},
        {id:165,cantidad:'POCO',color:'ROJO',forma:'U invertida',calvicie:'chica',implantacion:'grande',},
        {id:166,cantidad:'POCO',color:'ROJO',forma:'U invertida',calvicie:'mediana',implantacion:'chica',},
        {id:167,cantidad:'POCO',color:'ROJO',forma:'U invertida',calvicie:'mediana',implantacion:'mediana',},
        {id:168,cantidad:'POCO',color:'ROJO',forma:'U invertida',calvicie:'mediana',implantacion:'grande',},
        {id:169,cantidad:'POCO',color:'ROJO',forma:'U invertida',calvicie:'grande',implantacion:'chica',},
        {id:170,cantidad:'POCO',color:'ROJO',forma:'U invertida',calvicie:'grande',implantacion:'mediana',},
        {id:171,cantidad:'POCO',color:'ROJO',forma:'U invertida',calvicie:'grande',implantacion:'grande',},
        {id:172,cantidad:'POCO',color:'ROJO',forma:'Rapada',calvicie:'chica',implantacion:'chica',},
        {id:173,cantidad:'POCO',color:'ROJO',forma:'Rapada',calvicie:'chica',implantacion:'mediana',},
        {id:174,cantidad:'POCO',color:'ROJO',forma:'Rapada',calvicie:'chica',implantacion:'grande',},
        {id:175,cantidad:'POCO',color:'ROJO',forma:'Rapada',calvicie:'mediana',implantacion:'chica',},
        {id:176,cantidad:'POCO',color:'ROJO',forma:'Rapada',calvicie:'mediana',implantacion:'mediana',},
        {id:177,cantidad:'POCO',color:'ROJO',forma:'Rapada',calvicie:'mediana',implantacion:'grande',},
        {id:178,cantidad:'POCO',color:'ROJO',forma:'Rapada',calvicie:'grande',implantacion:'chica',},
        {id:179,cantidad:'POCO',color:'ROJO',forma:'Rapada',calvicie:'grande',implantacion:'mediana',},
        {id:180,cantidad:'POCO',color:'ROJO',forma:'Rapada',calvicie:'grande',implantacion:'grande',},
        {id:181,cantidad:'MEDIO',color:'AZUL',forma:'Recta',calvicie:'chica',implantacion:'chica',},
        {id:182,cantidad:'MEDIO',color:'AZUL',forma:'Recta',calvicie:'chica',implantacion:'mediana',},
        {id:183,cantidad:'MEDIO',color:'AZUL',forma:'Recta',calvicie:'chica',implantacion:'grande',},
        {id:184,cantidad:'MEDIO',color:'AZUL',forma:'Recta',calvicie:'mediana',implantacion:'chica',},
        {id:185,cantidad:'MEDIO',color:'AZUL',forma:'Recta',calvicie:'mediana',implantacion:'mediana',},
        {id:186,cantidad:'MEDIO',color:'AZUL',forma:'Recta',calvicie:'mediana',implantacion:'grande',},
        {id:187,cantidad:'MEDIO',color:'AZUL',forma:'Recta',calvicie:'grande',implantacion:'chica',},
        {id:188,cantidad:'MEDIO',color:'AZUL',forma:'Recta',calvicie:'grande',implantacion:'mediana',},
        {id:189,cantidad:'MEDIO',color:'AZUL',forma:'Recta',calvicie:'grande',implantacion:'grande',},
        {id:190,cantidad:'MEDIO',color:'AZUL',forma:'S',calvicie:'chica',implantacion:'chica',},
        {id:191,cantidad:'MEDIO',color:'AZUL',forma:'S',calvicie:'chica',implantacion:'mediana',},
        {id:192,cantidad:'MEDIO',color:'AZUL',forma:'S',calvicie:'chica',implantacion:'grande',},
        {id:193,cantidad:'MEDIO',color:'AZUL',forma:'S',calvicie:'mediana',implantacion:'chica',},
        {id:194,cantidad:'MEDIO',color:'AZUL',forma:'S',calvicie:'mediana',implantacion:'mediana',},
        {id:195,cantidad:'MEDIO',color:'AZUL',forma:'S',calvicie:'mediana',implantacion:'grande',},
        {id:196,cantidad:'MEDIO',color:'AZUL',forma:'S',calvicie:'grande',implantacion:'chica',},
        {id:197,cantidad:'MEDIO',color:'AZUL',forma:'S',calvicie:'grande',implantacion:'mediana',},
        {id:198,cantidad:'MEDIO',color:'AZUL',forma:'S',calvicie:'grande',implantacion:'grande',},
        {id:199,cantidad:'MEDIO',color:'AZUL',forma:'U',calvicie:'chica',implantacion:'chica',},
        {id:200,cantidad:'MEDIO',color:'AZUL',forma:'U',calvicie:'chica',implantacion:'mediana',},
        {id:201,cantidad:'MEDIO',color:'AZUL',forma:'U',calvicie:'chica',implantacion:'grande',},
        {id:202,cantidad:'MEDIO',color:'AZUL',forma:'U',calvicie:'mediana',implantacion:'chica',},
        {id:203,cantidad:'MEDIO',color:'AZUL',forma:'U',calvicie:'mediana',implantacion:'mediana',},
        {id:204,cantidad:'MEDIO',color:'AZUL',forma:'U',calvicie:'mediana',implantacion:'grande',},
        {id:205,cantidad:'MEDIO',color:'AZUL',forma:'U',calvicie:'grande',implantacion:'chica',},
        {id:206,cantidad:'MEDIO',color:'AZUL',forma:'U',calvicie:'grande',implantacion:'mediana',},
        {id:207,cantidad:'MEDIO',color:'AZUL',forma:'U',calvicie:'grande',implantacion:'grande',},
        {id:208,cantidad:'MEDIO',color:'AZUL',forma:'U invertida',calvicie:'chica',implantacion:'chica',},
        {id:209,cantidad:'MEDIO',color:'AZUL',forma:'U invertida',calvicie:'chica',implantacion:'mediana',},
        {id:210,cantidad:'MEDIO',color:'AZUL',forma:'U invertida',calvicie:'chica',implantacion:'grande',},
        {id:211,cantidad:'MEDIO',color:'AZUL',forma:'U invertida',calvicie:'mediana',implantacion:'chica',},
        {id:212,cantidad:'MEDIO',color:'AZUL',forma:'U invertida',calvicie:'mediana',implantacion:'mediana',},
        {id:213,cantidad:'MEDIO',color:'AZUL',forma:'U invertida',calvicie:'mediana',implantacion:'grande',},
        {id:214,cantidad:'MEDIO',color:'AZUL',forma:'U invertida',calvicie:'grande',implantacion:'chica',},
        {id:215,cantidad:'MEDIO',color:'AZUL',forma:'U invertida',calvicie:'grande',implantacion:'mediana',},
        {id:216,cantidad:'MEDIO',color:'AZUL',forma:'U invertida',calvicie:'grande',implantacion:'grande',},
        {id:217,cantidad:'MEDIO',color:'AZUL',forma:'Rapada',calvicie:'chica',implantacion:'chica',},
        {id:218,cantidad:'MEDIO',color:'AZUL',forma:'Rapada',calvicie:'chica',implantacion:'mediana',},
        {id:219,cantidad:'MEDIO',color:'AZUL',forma:'Rapada',calvicie:'chica',implantacion:'grande',},
        {id:220,cantidad:'MEDIO',color:'AZUL',forma:'Rapada',calvicie:'mediana',implantacion:'chica',},
        {id:221,cantidad:'MEDIO',color:'AZUL',forma:'Rapada',calvicie:'mediana',implantacion:'mediana',},
        {id:222,cantidad:'MEDIO',color:'AZUL',forma:'Rapada',calvicie:'mediana',implantacion:'grande',},
        {id:223,cantidad:'MEDIO',color:'AZUL',forma:'Rapada',calvicie:'grande',implantacion:'chica',},
        {id:224,cantidad:'MEDIO',color:'AZUL',forma:'Rapada',calvicie:'grande',implantacion:'mediana',},
        {id:225,cantidad:'MEDIO',color:'AZUL',forma:'Rapada',calvicie:'grande',implantacion:'grande',},
        {id:226,cantidad:'MEDIO',color:'NEGRO',forma:'Recta',calvicie:'chica',implantacion:'chica',},
        {id:227,cantidad:'MEDIO',color:'NEGRO',forma:'Recta',calvicie:'chica',implantacion:'mediana',},
        {id:228,cantidad:'MEDIO',color:'NEGRO',forma:'Recta',calvicie:'chica',implantacion:'grande',},
        {id:229,cantidad:'MEDIO',color:'NEGRO',forma:'Recta',calvicie:'mediana',implantacion:'chica',},
        {id:230,cantidad:'MEDIO',color:'NEGRO',forma:'Recta',calvicie:'mediana',implantacion:'mediana',},
        {id:231,cantidad:'MEDIO',color:'NEGRO',forma:'Recta',calvicie:'mediana',implantacion:'grande',},
        {id:232,cantidad:'MEDIO',color:'NEGRO',forma:'Recta',calvicie:'grande',implantacion:'chica',},
        {id:233,cantidad:'MEDIO',color:'NEGRO',forma:'Recta',calvicie:'grande',implantacion:'mediana',},
        {id:234,cantidad:'MEDIO',color:'NEGRO',forma:'Recta',calvicie:'grande',implantacion:'grande',},
        {id:235,cantidad:'MEDIO',color:'NEGRO',forma:'S',calvicie:'chica',implantacion:'chica',},
        {id:236,cantidad:'MEDIO',color:'NEGRO',forma:'S',calvicie:'chica',implantacion:'mediana',},
        {id:237,cantidad:'MEDIO',color:'NEGRO',forma:'S',calvicie:'chica',implantacion:'grande',},
        {id:238,cantidad:'MEDIO',color:'NEGRO',forma:'S',calvicie:'mediana',implantacion:'chica',},
        {id:239,cantidad:'MEDIO',color:'NEGRO',forma:'S',calvicie:'mediana',implantacion:'mediana',},
        {id:240,cantidad:'MEDIO',color:'NEGRO',forma:'S',calvicie:'mediana',implantacion:'grande',},
        {id:241,cantidad:'MEDIO',color:'NEGRO',forma:'S',calvicie:'grande',implantacion:'chica',},
        {id:242,cantidad:'MEDIO',color:'NEGRO',forma:'S',calvicie:'grande',implantacion:'mediana',},
        {id:243,cantidad:'MEDIO',color:'NEGRO',forma:'S',calvicie:'grande',implantacion:'grande',},
        {id:244,cantidad:'MEDIO',color:'NEGRO',forma:'U',calvicie:'chica',implantacion:'chica',},
        {id:245,cantidad:'MEDIO',color:'NEGRO',forma:'U',calvicie:'chica',implantacion:'mediana',},
        {id:246,cantidad:'MEDIO',color:'NEGRO',forma:'U',calvicie:'chica',implantacion:'grande',},
        {id:247,cantidad:'MEDIO',color:'NEGRO',forma:'U',calvicie:'mediana',implantacion:'chica',},
        {id:248,cantidad:'MEDIO',color:'NEGRO',forma:'U',calvicie:'mediana',implantacion:'mediana',},
        {id:249,cantidad:'MEDIO',color:'NEGRO',forma:'U',calvicie:'mediana',implantacion:'grande',},
        {id:250,cantidad:'MEDIO',color:'NEGRO',forma:'U',calvicie:'grande',implantacion:'chica',},
        {id:251,cantidad:'MEDIO',color:'NEGRO',forma:'U',calvicie:'grande',implantacion:'mediana',},
        {id:252,cantidad:'MEDIO',color:'NEGRO',forma:'U',calvicie:'grande',implantacion:'grande',},
        {id:253,cantidad:'MEDIO',color:'NEGRO',forma:'U invertida',calvicie:'chica',implantacion:'chica',},
        {id:254,cantidad:'MEDIO',color:'NEGRO',forma:'U invertida',calvicie:'chica',implantacion:'mediana',},
        {id:255,cantidad:'MEDIO',color:'NEGRO',forma:'U invertida',calvicie:'chica',implantacion:'grande',},
        {id:256,cantidad:'MEDIO',color:'NEGRO',forma:'U invertida',calvicie:'mediana',implantacion:'chica',},
        {id:257,cantidad:'MEDIO',color:'NEGRO',forma:'U invertida',calvicie:'mediana',implantacion:'mediana',},
        {id:258,cantidad:'MEDIO',color:'NEGRO',forma:'U invertida',calvicie:'mediana',implantacion:'grande',},
        {id:259,cantidad:'MEDIO',color:'NEGRO',forma:'U invertida',calvicie:'grande',implantacion:'chica',},
        {id:260,cantidad:'MEDIO',color:'NEGRO',forma:'U invertida',calvicie:'grande',implantacion:'mediana',},
        {id:261,cantidad:'MEDIO',color:'NEGRO',forma:'U invertida',calvicie:'grande',implantacion:'grande',},
        {id:262,cantidad:'MEDIO',color:'NEGRO',forma:'Rapada',calvicie:'chica',implantacion:'chica',},
        {id:263,cantidad:'MEDIO',color:'NEGRO',forma:'Rapada',calvicie:'chica',implantacion:'mediana',},
        {id:264,cantidad:'MEDIO',color:'NEGRO',forma:'Rapada',calvicie:'chica',implantacion:'grande',},
        {id:265,cantidad:'MEDIO',color:'NEGRO',forma:'Rapada',calvicie:'mediana',implantacion:'chica',},
        {id:266,cantidad:'MEDIO',color:'NEGRO',forma:'Rapada',calvicie:'mediana',implantacion:'mediana',},
        {id:267,cantidad:'MEDIO',color:'NEGRO',forma:'Rapada',calvicie:'mediana',implantacion:'grande',},
        {id:268,cantidad:'MEDIO',color:'NEGRO',forma:'Rapada',calvicie:'grande',implantacion:'chica',},
        {id:269,cantidad:'MEDIO',color:'NEGRO',forma:'Rapada',calvicie:'grande',implantacion:'mediana',},
        {id:270,cantidad:'MEDIO',color:'NEGRO',forma:'Rapada',calvicie:'grande',implantacion:'grande',},
        {id:271,cantidad:'MEDIO',color:'CAFE',forma:'Recta',calvicie:'chica',implantacion:'chica',},
        {id:272,cantidad:'MEDIO',color:'CAFE',forma:'Recta',calvicie:'chica',implantacion:'mediana',},
        {id:273,cantidad:'MEDIO',color:'CAFE',forma:'Recta',calvicie:'chica',implantacion:'grande',},
        {id:274,cantidad:'MEDIO',color:'CAFE',forma:'Recta',calvicie:'mediana',implantacion:'chica',},
        {id:275,cantidad:'MEDIO',color:'CAFE',forma:'Recta',calvicie:'mediana',implantacion:'mediana',},
        {id:276,cantidad:'MEDIO',color:'CAFE',forma:'Recta',calvicie:'mediana',implantacion:'grande',},
        {id:277,cantidad:'MEDIO',color:'CAFE',forma:'Recta',calvicie:'grande',implantacion:'chica',},
        {id:278,cantidad:'MEDIO',color:'CAFE',forma:'Recta',calvicie:'grande',implantacion:'mediana',},
        {id:279,cantidad:'MEDIO',color:'CAFE',forma:'Recta',calvicie:'grande',implantacion:'grande',},
        {id:280,cantidad:'MEDIO',color:'CAFE',forma:'S',calvicie:'chica',implantacion:'chica',},
        {id:281,cantidad:'MEDIO',color:'CAFE',forma:'S',calvicie:'chica',implantacion:'mediana',},
        {id:282,cantidad:'MEDIO',color:'CAFE',forma:'S',calvicie:'chica',implantacion:'grande',},
        {id:283,cantidad:'MEDIO',color:'CAFE',forma:'S',calvicie:'mediana',implantacion:'chica',},
        {id:284,cantidad:'MEDIO',color:'CAFE',forma:'S',calvicie:'mediana',implantacion:'mediana',},
        {id:285,cantidad:'MEDIO',color:'CAFE',forma:'S',calvicie:'mediana',implantacion:'grande',},
        {id:286,cantidad:'MEDIO',color:'CAFE',forma:'S',calvicie:'grande',implantacion:'chica',},
        {id:287,cantidad:'MEDIO',color:'CAFE',forma:'S',calvicie:'grande',implantacion:'mediana',},
        {id:288,cantidad:'MEDIO',color:'CAFE',forma:'S',calvicie:'grande',implantacion:'grande',},
        {id:289,cantidad:'MEDIO',color:'CAFE',forma:'U',calvicie:'chica',implantacion:'chica',},
        {id:290,cantidad:'MEDIO',color:'CAFE',forma:'U',calvicie:'chica',implantacion:'mediana',},
        {id:291,cantidad:'MEDIO',color:'CAFE',forma:'U',calvicie:'chica',implantacion:'grande',},
        {id:292,cantidad:'MEDIO',color:'CAFE',forma:'U',calvicie:'mediana',implantacion:'chica',},
        {id:293,cantidad:'MEDIO',color:'CAFE',forma:'U',calvicie:'mediana',implantacion:'mediana',},
        {id:294,cantidad:'MEDIO',color:'CAFE',forma:'U',calvicie:'mediana',implantacion:'grande',},
        {id:295,cantidad:'MEDIO',color:'CAFE',forma:'U',calvicie:'grande',implantacion:'chica',},
        {id:296,cantidad:'MEDIO',color:'CAFE',forma:'U',calvicie:'grande',implantacion:'mediana',},
        {id:297,cantidad:'MEDIO',color:'CAFE',forma:'U',calvicie:'grande',implantacion:'grande',},
        {id:298,cantidad:'MEDIO',color:'CAFE',forma:'U invertida',calvicie:'chica',implantacion:'chica',},
        {id:299,cantidad:'MEDIO',color:'CAFE',forma:'U invertida',calvicie:'chica',implantacion:'mediana',},
        {id:300,cantidad:'MEDIO',color:'CAFE',forma:'U invertida',calvicie:'chica',implantacion:'grande',},
        {id:301,cantidad:'MEDIO',color:'CAFE',forma:'U invertida',calvicie:'mediana',implantacion:'chica',},
        {id:302,cantidad:'MEDIO',color:'CAFE',forma:'U invertida',calvicie:'mediana',implantacion:'mediana',},
        {id:303,cantidad:'MEDIO',color:'CAFE',forma:'U invertida',calvicie:'mediana',implantacion:'grande',},
        {id:304,cantidad:'MEDIO',color:'CAFE',forma:'U invertida',calvicie:'grande',implantacion:'chica',},
        {id:305,cantidad:'MEDIO',color:'CAFE',forma:'U invertida',calvicie:'grande',implantacion:'mediana',},
        {id:306,cantidad:'MEDIO',color:'CAFE',forma:'U invertida',calvicie:'grande',implantacion:'grande',},
        {id:307,cantidad:'MEDIO',color:'CAFE',forma:'Rapada',calvicie:'chica',implantacion:'chica',},
        {id:308,cantidad:'MEDIO',color:'CAFE',forma:'Rapada',calvicie:'chica',implantacion:'mediana',},
        {id:309,cantidad:'MEDIO',color:'CAFE',forma:'Rapada',calvicie:'chica',implantacion:'grande',},
        {id:310,cantidad:'MEDIO',color:'CAFE',forma:'Rapada',calvicie:'mediana',implantacion:'chica',},
        {id:311,cantidad:'MEDIO',color:'CAFE',forma:'Rapada',calvicie:'mediana',implantacion:'mediana',},
        {id:312,cantidad:'MEDIO',color:'CAFE',forma:'Rapada',calvicie:'mediana',implantacion:'grande',},
        {id:313,cantidad:'MEDIO',color:'CAFE',forma:'Rapada',calvicie:'grande',implantacion:'chica',},
        {id:314,cantidad:'MEDIO',color:'CAFE',forma:'Rapada',calvicie:'grande',implantacion:'mediana',},
        {id:315,cantidad:'MEDIO',color:'CAFE',forma:'Rapada',calvicie:'grande',implantacion:'grande',},
        {id:316,cantidad:'MEDIO',color:'ROJO',forma:'Recta',calvicie:'chica',implantacion:'chica',},
        {id:317,cantidad:'MEDIO',color:'ROJO',forma:'Recta',calvicie:'chica',implantacion:'mediana',},
        {id:318,cantidad:'MEDIO',color:'ROJO',forma:'Recta',calvicie:'chica',implantacion:'grande',},
        {id:319,cantidad:'MEDIO',color:'ROJO',forma:'Recta',calvicie:'mediana',implantacion:'chica',},
        {id:320,cantidad:'MEDIO',color:'ROJO',forma:'Recta',calvicie:'mediana',implantacion:'mediana',},
        {id:321,cantidad:'MEDIO',color:'ROJO',forma:'Recta',calvicie:'mediana',implantacion:'grande',},
        {id:322,cantidad:'MEDIO',color:'ROJO',forma:'Recta',calvicie:'grande',implantacion:'chica',},
        {id:323,cantidad:'MEDIO',color:'ROJO',forma:'Recta',calvicie:'grande',implantacion:'mediana',},
        {id:324,cantidad:'MEDIO',color:'ROJO',forma:'Recta',calvicie:'grande',implantacion:'grande',},
        {id:325,cantidad:'MEDIO',color:'ROJO',forma:'S',calvicie:'chica',implantacion:'chica',},
        {id:326,cantidad:'MEDIO',color:'ROJO',forma:'S',calvicie:'chica',implantacion:'mediana',},
        {id:327,cantidad:'MEDIO',color:'ROJO',forma:'S',calvicie:'chica',implantacion:'grande',},
        {id:328,cantidad:'MEDIO',color:'ROJO',forma:'S',calvicie:'mediana',implantacion:'chica',},
        {id:329,cantidad:'MEDIO',color:'ROJO',forma:'S',calvicie:'mediana',implantacion:'mediana',},
        {id:330,cantidad:'MEDIO',color:'ROJO',forma:'S',calvicie:'mediana',implantacion:'grande',},
        {id:331,cantidad:'MEDIO',color:'ROJO',forma:'S',calvicie:'grande',implantacion:'chica',},
        {id:332,cantidad:'MEDIO',color:'ROJO',forma:'S',calvicie:'grande',implantacion:'mediana',},
        {id:333,cantidad:'MEDIO',color:'ROJO',forma:'S',calvicie:'grande',implantacion:'grande',},
        {id:334,cantidad:'MEDIO',color:'ROJO',forma:'U',calvicie:'chica',implantacion:'chica',},
        {id:335,cantidad:'MEDIO',color:'ROJO',forma:'U',calvicie:'chica',implantacion:'mediana',},
        {id:336,cantidad:'MEDIO',color:'ROJO',forma:'U',calvicie:'chica',implantacion:'grande',},
        {id:337,cantidad:'MEDIO',color:'ROJO',forma:'U',calvicie:'mediana',implantacion:'chica',},
        {id:338,cantidad:'MEDIO',color:'ROJO',forma:'U',calvicie:'mediana',implantacion:'mediana',},
        {id:339,cantidad:'MEDIO',color:'ROJO',forma:'U',calvicie:'mediana',implantacion:'grande',},
        {id:340,cantidad:'MEDIO',color:'ROJO',forma:'U',calvicie:'grande',implantacion:'chica',},
        {id:341,cantidad:'MEDIO',color:'ROJO',forma:'U',calvicie:'grande',implantacion:'mediana',},
        {id:342,cantidad:'MEDIO',color:'ROJO',forma:'U',calvicie:'grande',implantacion:'grande',},
        {id:343,cantidad:'MEDIO',color:'ROJO',forma:'U invertida',calvicie:'chica',implantacion:'chica',},
        {id:344,cantidad:'MEDIO',color:'ROJO',forma:'U invertida',calvicie:'chica',implantacion:'mediana',},
        {id:345,cantidad:'MEDIO',color:'ROJO',forma:'U invertida',calvicie:'chica',implantacion:'grande',},
        {id:346,cantidad:'MEDIO',color:'ROJO',forma:'U invertida',calvicie:'mediana',implantacion:'chica',},
        {id:347,cantidad:'MEDIO',color:'ROJO',forma:'U invertida',calvicie:'mediana',implantacion:'mediana',},
        {id:348,cantidad:'MEDIO',color:'ROJO',forma:'U invertida',calvicie:'mediana',implantacion:'grande',},
        {id:349,cantidad:'MEDIO',color:'ROJO',forma:'U invertida',calvicie:'grande',implantacion:'chica',},
        {id:350,cantidad:'MEDIO',color:'ROJO',forma:'U invertida',calvicie:'grande',implantacion:'mediana',},
        {id:351,cantidad:'MEDIO',color:'ROJO',forma:'U invertida',calvicie:'grande',implantacion:'grande',},
        {id:352,cantidad:'MEDIO',color:'ROJO',forma:'Rapada',calvicie:'chica',implantacion:'chica',},
        {id:353,cantidad:'MEDIO',color:'ROJO',forma:'Rapada',calvicie:'chica',implantacion:'mediana',},
        {id:354,cantidad:'MEDIO',color:'ROJO',forma:'Rapada',calvicie:'chica',implantacion:'grande',},
        {id:355,cantidad:'MEDIO',color:'ROJO',forma:'Rapada',calvicie:'mediana',implantacion:'chica',},
        {id:356,cantidad:'MEDIO',color:'ROJO',forma:'Rapada',calvicie:'mediana',implantacion:'mediana',},
        {id:357,cantidad:'MEDIO',color:'ROJO',forma:'Rapada',calvicie:'mediana',implantacion:'grande',},
        {id:358,cantidad:'MEDIO',color:'ROJO',forma:'Rapada',calvicie:'grande',implantacion:'chica',},
        {id:359,cantidad:'MEDIO',color:'ROJO',forma:'Rapada',calvicie:'grande',implantacion:'mediana',},
        {id:360,cantidad:'MEDIO',color:'ROJO',forma:'Rapada',calvicie:'grande',implantacion:'grande',},
        {id:361,cantidad:'MUCHO',color:'AZUL',forma:'Recta',calvicie:'chica',implantacion:'chica',},
        {id:362,cantidad:'MUCHO',color:'AZUL',forma:'Recta',calvicie:'chica',implantacion:'mediana',},
        {id:363,cantidad:'MUCHO',color:'AZUL',forma:'Recta',calvicie:'chica',implantacion:'grande',},
        {id:364,cantidad:'MUCHO',color:'AZUL',forma:'Recta',calvicie:'mediana',implantacion:'chica',},
        {id:365,cantidad:'MUCHO',color:'AZUL',forma:'Recta',calvicie:'mediana',implantacion:'mediana',},
        {id:366,cantidad:'MUCHO',color:'AZUL',forma:'Recta',calvicie:'mediana',implantacion:'grande',},
        {id:367,cantidad:'MUCHO',color:'AZUL',forma:'Recta',calvicie:'grande',implantacion:'chica',},
        {id:368,cantidad:'MUCHO',color:'AZUL',forma:'Recta',calvicie:'grande',implantacion:'mediana',},
        {id:369,cantidad:'MUCHO',color:'AZUL',forma:'Recta',calvicie:'grande',implantacion:'grande',},
        {id:370,cantidad:'MUCHO',color:'AZUL',forma:'S',calvicie:'chica',implantacion:'chica',},
        {id:371,cantidad:'MUCHO',color:'AZUL',forma:'S',calvicie:'chica',implantacion:'mediana',},
        {id:372,cantidad:'MUCHO',color:'AZUL',forma:'S',calvicie:'chica',implantacion:'grande',},
        {id:373,cantidad:'MUCHO',color:'AZUL',forma:'S',calvicie:'mediana',implantacion:'chica',},
        {id:374,cantidad:'MUCHO',color:'AZUL',forma:'S',calvicie:'mediana',implantacion:'mediana',},
        {id:375,cantidad:'MUCHO',color:'AZUL',forma:'S',calvicie:'mediana',implantacion:'grande',},
        {id:376,cantidad:'MUCHO',color:'AZUL',forma:'S',calvicie:'grande',implantacion:'chica',},
        {id:377,cantidad:'MUCHO',color:'AZUL',forma:'S',calvicie:'grande',implantacion:'mediana',},
        {id:378,cantidad:'MUCHO',color:'AZUL',forma:'S',calvicie:'grande',implantacion:'grande',},
        {id:379,cantidad:'MUCHO',color:'AZUL',forma:'U',calvicie:'chica',implantacion:'chica',},
        {id:380,cantidad:'MUCHO',color:'AZUL',forma:'U',calvicie:'chica',implantacion:'mediana',},
        {id:381,cantidad:'MUCHO',color:'AZUL',forma:'U',calvicie:'chica',implantacion:'grande',},
        {id:382,cantidad:'MUCHO',color:'AZUL',forma:'U',calvicie:'mediana',implantacion:'chica',},
        {id:383,cantidad:'MUCHO',color:'AZUL',forma:'U',calvicie:'mediana',implantacion:'mediana',},
        {id:384,cantidad:'MUCHO',color:'AZUL',forma:'U',calvicie:'mediana',implantacion:'grande',},
        {id:385,cantidad:'MUCHO',color:'AZUL',forma:'U',calvicie:'grande',implantacion:'chica',},
        {id:386,cantidad:'MUCHO',color:'AZUL',forma:'U',calvicie:'grande',implantacion:'mediana',},
        {id:387,cantidad:'MUCHO',color:'AZUL',forma:'U',calvicie:'grande',implantacion:'grande',},
        {id:388,cantidad:'MUCHO',color:'AZUL',forma:'U invertida',calvicie:'chica',implantacion:'chica',},
        {id:389,cantidad:'MUCHO',color:'AZUL',forma:'U invertida',calvicie:'chica',implantacion:'mediana',},
        {id:390,cantidad:'MUCHO',color:'AZUL',forma:'U invertida',calvicie:'chica',implantacion:'grande',},
        {id:391,cantidad:'MUCHO',color:'AZUL',forma:'U invertida',calvicie:'mediana',implantacion:'chica',},
        {id:392,cantidad:'MUCHO',color:'AZUL',forma:'U invertida',calvicie:'mediana',implantacion:'mediana',},
        {id:393,cantidad:'MUCHO',color:'AZUL',forma:'U invertida',calvicie:'mediana',implantacion:'grande',},
        {id:394,cantidad:'MUCHO',color:'AZUL',forma:'U invertida',calvicie:'grande',implantacion:'chica',},
        {id:395,cantidad:'MUCHO',color:'AZUL',forma:'U invertida',calvicie:'grande',implantacion:'mediana',},
        {id:396,cantidad:'MUCHO',color:'AZUL',forma:'U invertida',calvicie:'grande',implantacion:'grande',},
        {id:397,cantidad:'MUCHO',color:'AZUL',forma:'Rapada',calvicie:'chica',implantacion:'chica',},
        {id:398,cantidad:'MUCHO',color:'AZUL',forma:'Rapada',calvicie:'chica',implantacion:'mediana',},
        {id:399,cantidad:'MUCHO',color:'AZUL',forma:'Rapada',calvicie:'chica',implantacion:'grande',},
        {id:400,cantidad:'MUCHO',color:'AZUL',forma:'Rapada',calvicie:'mediana',implantacion:'chica',},
        {id:401,cantidad:'MUCHO',color:'AZUL',forma:'Rapada',calvicie:'mediana',implantacion:'mediana',},
        {id:402,cantidad:'MUCHO',color:'AZUL',forma:'Rapada',calvicie:'mediana',implantacion:'grande',},
        {id:403,cantidad:'MUCHO',color:'AZUL',forma:'Rapada',calvicie:'grande',implantacion:'chica',},
        {id:404,cantidad:'MUCHO',color:'AZUL',forma:'Rapada',calvicie:'grande',implantacion:'mediana',},
        {id:405,cantidad:'MUCHO',color:'AZUL',forma:'Rapada',calvicie:'grande',implantacion:'grande',},
        {id:406,cantidad:'MUCHO',color:'NEGRO',forma:'Recta',calvicie:'chica',implantacion:'chica',},
        {id:407,cantidad:'MUCHO',color:'NEGRO',forma:'Recta',calvicie:'chica',implantacion:'mediana',},
        {id:408,cantidad:'MUCHO',color:'NEGRO',forma:'Recta',calvicie:'chica',implantacion:'grande',},
        {id:409,cantidad:'MUCHO',color:'NEGRO',forma:'Recta',calvicie:'mediana',implantacion:'chica',},
        {id:410,cantidad:'MUCHO',color:'NEGRO',forma:'Recta',calvicie:'mediana',implantacion:'mediana',},
        {id:411,cantidad:'MUCHO',color:'NEGRO',forma:'Recta',calvicie:'mediana',implantacion:'grande',},
        {id:412,cantidad:'MUCHO',color:'NEGRO',forma:'Recta',calvicie:'grande',implantacion:'chica',},
        {id:413,cantidad:'MUCHO',color:'NEGRO',forma:'Recta',calvicie:'grande',implantacion:'mediana',},
        {id:414,cantidad:'MUCHO',color:'NEGRO',forma:'Recta',calvicie:'grande',implantacion:'grande',},
        {id:415,cantidad:'MUCHO',color:'NEGRO',forma:'S',calvicie:'chica',implantacion:'chica',},
        {id:416,cantidad:'MUCHO',color:'NEGRO',forma:'S',calvicie:'chica',implantacion:'mediana',},
        {id:417,cantidad:'MUCHO',color:'NEGRO',forma:'S',calvicie:'chica',implantacion:'grande',},
        {id:418,cantidad:'MUCHO',color:'NEGRO',forma:'S',calvicie:'mediana',implantacion:'chica',},
        {id:419,cantidad:'MUCHO',color:'NEGRO',forma:'S',calvicie:'mediana',implantacion:'mediana',},
        {id:420,cantidad:'MUCHO',color:'NEGRO',forma:'S',calvicie:'mediana',implantacion:'grande',},
        {id:421,cantidad:'MUCHO',color:'NEGRO',forma:'S',calvicie:'grande',implantacion:'chica',},
        {id:422,cantidad:'MUCHO',color:'NEGRO',forma:'S',calvicie:'grande',implantacion:'mediana',},
        {id:423,cantidad:'MUCHO',color:'NEGRO',forma:'S',calvicie:'grande',implantacion:'grande',},
        {id:424,cantidad:'MUCHO',color:'NEGRO',forma:'U',calvicie:'chica',implantacion:'chica',},
        {id:425,cantidad:'MUCHO',color:'NEGRO',forma:'U',calvicie:'chica',implantacion:'mediana',},
        {id:426,cantidad:'MUCHO',color:'NEGRO',forma:'U',calvicie:'chica',implantacion:'grande',},
        {id:427,cantidad:'MUCHO',color:'NEGRO',forma:'U',calvicie:'mediana',implantacion:'chica',},
        {id:428,cantidad:'MUCHO',color:'NEGRO',forma:'U',calvicie:'mediana',implantacion:'mediana',},
        {id:429,cantidad:'MUCHO',color:'NEGRO',forma:'U',calvicie:'mediana',implantacion:'grande',},
        {id:430,cantidad:'MUCHO',color:'NEGRO',forma:'U',calvicie:'grande',implantacion:'chica',},
        {id:431,cantidad:'MUCHO',color:'NEGRO',forma:'U',calvicie:'grande',implantacion:'mediana',},
        {id:432,cantidad:'MUCHO',color:'NEGRO',forma:'U',calvicie:'grande',implantacion:'grande',},
        {id:433,cantidad:'MUCHO',color:'NEGRO',forma:'U invertida',calvicie:'chica',implantacion:'chica',},
        {id:434,cantidad:'MUCHO',color:'NEGRO',forma:'U invertida',calvicie:'chica',implantacion:'mediana',},
        {id:435,cantidad:'MUCHO',color:'NEGRO',forma:'U invertida',calvicie:'chica',implantacion:'grande',},
        {id:436,cantidad:'MUCHO',color:'NEGRO',forma:'U invertida',calvicie:'mediana',implantacion:'chica',},
        {id:437,cantidad:'MUCHO',color:'NEGRO',forma:'U invertida',calvicie:'mediana',implantacion:'mediana',},
        {id:438,cantidad:'MUCHO',color:'NEGRO',forma:'U invertida',calvicie:'mediana',implantacion:'grande',},
        {id:439,cantidad:'MUCHO',color:'NEGRO',forma:'U invertida',calvicie:'grande',implantacion:'chica',},
        {id:440,cantidad:'MUCHO',color:'NEGRO',forma:'U invertida',calvicie:'grande',implantacion:'mediana',},
        {id:441,cantidad:'MUCHO',color:'NEGRO',forma:'U invertida',calvicie:'grande',implantacion:'grande',},
        {id:442,cantidad:'MUCHO',color:'NEGRO',forma:'Rapada',calvicie:'chica',implantacion:'chica',},
        {id:443,cantidad:'MUCHO',color:'NEGRO',forma:'Rapada',calvicie:'chica',implantacion:'mediana',},
        {id:444,cantidad:'MUCHO',color:'NEGRO',forma:'Rapada',calvicie:'chica',implantacion:'grande',},
        {id:445,cantidad:'MUCHO',color:'NEGRO',forma:'Rapada',calvicie:'mediana',implantacion:'chica',},
        {id:446,cantidad:'MUCHO',color:'NEGRO',forma:'Rapada',calvicie:'mediana',implantacion:'mediana',},
        {id:447,cantidad:'MUCHO',color:'NEGRO',forma:'Rapada',calvicie:'mediana',implantacion:'grande',},
        {id:448,cantidad:'MUCHO',color:'NEGRO',forma:'Rapada',calvicie:'grande',implantacion:'chica',},
        {id:449,cantidad:'MUCHO',color:'NEGRO',forma:'Rapada',calvicie:'grande',implantacion:'mediana',},
        {id:450,cantidad:'MUCHO',color:'NEGRO',forma:'Rapada',calvicie:'grande',implantacion:'grande',},
        {id:451,cantidad:'MUCHO',color:'CAFE',forma:'Recta',calvicie:'chica',implantacion:'chica',},
        {id:452,cantidad:'MUCHO',color:'CAFE',forma:'Recta',calvicie:'chica',implantacion:'mediana',},
        {id:453,cantidad:'MUCHO',color:'CAFE',forma:'Recta',calvicie:'chica',implantacion:'grande',},
        {id:454,cantidad:'MUCHO',color:'CAFE',forma:'Recta',calvicie:'mediana',implantacion:'chica',},
        {id:455,cantidad:'MUCHO',color:'CAFE',forma:'Recta',calvicie:'mediana',implantacion:'mediana',},
        {id:456,cantidad:'MUCHO',color:'CAFE',forma:'Recta',calvicie:'mediana',implantacion:'grande',},
        {id:457,cantidad:'MUCHO',color:'CAFE',forma:'Recta',calvicie:'grande',implantacion:'chica',},
        {id:458,cantidad:'MUCHO',color:'CAFE',forma:'Recta',calvicie:'grande',implantacion:'mediana',},
        {id:459,cantidad:'MUCHO',color:'CAFE',forma:'Recta',calvicie:'grande',implantacion:'grande',},
        {id:460,cantidad:'MUCHO',color:'CAFE',forma:'S',calvicie:'chica',implantacion:'chica',},
        {id:461,cantidad:'MUCHO',color:'CAFE',forma:'S',calvicie:'chica',implantacion:'mediana',},
        {id:462,cantidad:'MUCHO',color:'CAFE',forma:'S',calvicie:'chica',implantacion:'grande',},
        {id:463,cantidad:'MUCHO',color:'CAFE',forma:'S',calvicie:'mediana',implantacion:'chica',},
        {id:464,cantidad:'MUCHO',color:'CAFE',forma:'S',calvicie:'mediana',implantacion:'mediana',},
        {id:465,cantidad:'MUCHO',color:'CAFE',forma:'S',calvicie:'mediana',implantacion:'grande',},
        {id:466,cantidad:'MUCHO',color:'CAFE',forma:'S',calvicie:'grande',implantacion:'chica',},
        {id:467,cantidad:'MUCHO',color:'CAFE',forma:'S',calvicie:'grande',implantacion:'mediana',},
        {id:468,cantidad:'MUCHO',color:'CAFE',forma:'S',calvicie:'grande',implantacion:'grande',},
        {id:469,cantidad:'MUCHO',color:'CAFE',forma:'U',calvicie:'chica',implantacion:'chica',},
        {id:470,cantidad:'MUCHO',color:'CAFE',forma:'U',calvicie:'chica',implantacion:'mediana',},
        {id:471,cantidad:'MUCHO',color:'CAFE',forma:'U',calvicie:'chica',implantacion:'grande',},
        {id:472,cantidad:'MUCHO',color:'CAFE',forma:'U',calvicie:'mediana',implantacion:'chica',},
        {id:473,cantidad:'MUCHO',color:'CAFE',forma:'U',calvicie:'mediana',implantacion:'mediana',},
        {id:474,cantidad:'MUCHO',color:'CAFE',forma:'U',calvicie:'mediana',implantacion:'grande',},
        {id:475,cantidad:'MUCHO',color:'CAFE',forma:'U',calvicie:'grande',implantacion:'chica',},
        {id:476,cantidad:'MUCHO',color:'CAFE',forma:'U',calvicie:'grande',implantacion:'mediana',},
        {id:477,cantidad:'MUCHO',color:'CAFE',forma:'U',calvicie:'grande',implantacion:'grande',},
        {id:478,cantidad:'MUCHO',color:'CAFE',forma:'U invertida',calvicie:'chica',implantacion:'chica',},
        {id:479,cantidad:'MUCHO',color:'CAFE',forma:'U invertida',calvicie:'chica',implantacion:'mediana',},
        {id:480,cantidad:'MUCHO',color:'CAFE',forma:'U invertida',calvicie:'chica',implantacion:'grande',},
        {id:481,cantidad:'MUCHO',color:'CAFE',forma:'U invertida',calvicie:'mediana',implantacion:'chica',},
        {id:482,cantidad:'MUCHO',color:'CAFE',forma:'U invertida',calvicie:'mediana',implantacion:'mediana',},
        {id:483,cantidad:'MUCHO',color:'CAFE',forma:'U invertida',calvicie:'mediana',implantacion:'grande',},
        {id:484,cantidad:'MUCHO',color:'CAFE',forma:'U invertida',calvicie:'grande',implantacion:'chica',},
        {id:485,cantidad:'MUCHO',color:'CAFE',forma:'U invertida',calvicie:'grande',implantacion:'mediana',},
        {id:486,cantidad:'MUCHO',color:'CAFE',forma:'U invertida',calvicie:'grande',implantacion:'grande',},
        {id:487,cantidad:'MUCHO',color:'CAFE',forma:'Rapada',calvicie:'chica',implantacion:'chica',},
        {id:488,cantidad:'MUCHO',color:'CAFE',forma:'Rapada',calvicie:'chica',implantacion:'mediana',},
        {id:489,cantidad:'MUCHO',color:'CAFE',forma:'Rapada',calvicie:'chica',implantacion:'grande',},
        {id:490,cantidad:'MUCHO',color:'CAFE',forma:'Rapada',calvicie:'mediana',implantacion:'chica',},
        {id:491,cantidad:'MUCHO',color:'CAFE',forma:'Rapada',calvicie:'mediana',implantacion:'mediana',},
        {id:492,cantidad:'MUCHO',color:'CAFE',forma:'Rapada',calvicie:'mediana',implantacion:'grande',},
        {id:493,cantidad:'MUCHO',color:'CAFE',forma:'Rapada',calvicie:'grande',implantacion:'chica',},
        {id:494,cantidad:'MUCHO',color:'CAFE',forma:'Rapada',calvicie:'grande',implantacion:'mediana',},
        {id:495,cantidad:'MUCHO',color:'CAFE',forma:'Rapada',calvicie:'grande',implantacion:'grande',},
        {id:496,cantidad:'MUCHO',color:'ROJO',forma:'Recta',calvicie:'chica',implantacion:'chica',},
        {id:497,cantidad:'MUCHO',color:'ROJO',forma:'Recta',calvicie:'chica',implantacion:'mediana',},
        {id:498,cantidad:'MUCHO',color:'ROJO',forma:'Recta',calvicie:'chica',implantacion:'grande',},
        {id:499,cantidad:'MUCHO',color:'ROJO',forma:'Recta',calvicie:'mediana',implantacion:'chica',},
        {id:500,cantidad:'MUCHO',color:'ROJO',forma:'Recta',calvicie:'mediana',implantacion:'mediana',},
        {id:501,cantidad:'MUCHO',color:'ROJO',forma:'Recta',calvicie:'mediana',implantacion:'grande',},
        {id:502,cantidad:'MUCHO',color:'ROJO',forma:'Recta',calvicie:'grande',implantacion:'chica',},
        {id:503,cantidad:'MUCHO',color:'ROJO',forma:'Recta',calvicie:'grande',implantacion:'mediana',},
        {id:504,cantidad:'MUCHO',color:'ROJO',forma:'Recta',calvicie:'grande',implantacion:'grande',},
        {id:505,cantidad:'MUCHO',color:'ROJO',forma:'S',calvicie:'chica',implantacion:'chica',},
        {id:506,cantidad:'MUCHO',color:'ROJO',forma:'S',calvicie:'chica',implantacion:'mediana',},
        {id:507,cantidad:'MUCHO',color:'ROJO',forma:'S',calvicie:'chica',implantacion:'grande',},
        {id:508,cantidad:'MUCHO',color:'ROJO',forma:'S',calvicie:'mediana',implantacion:'chica',},
        {id:509,cantidad:'MUCHO',color:'ROJO',forma:'S',calvicie:'mediana',implantacion:'mediana',},
        {id:510,cantidad:'MUCHO',color:'ROJO',forma:'S',calvicie:'mediana',implantacion:'grande',},
        {id:511,cantidad:'MUCHO',color:'ROJO',forma:'S',calvicie:'grande',implantacion:'chica',},
        {id:512,cantidad:'MUCHO',color:'ROJO',forma:'S',calvicie:'grande',implantacion:'mediana',},
        {id:513,cantidad:'MUCHO',color:'ROJO',forma:'S',calvicie:'grande',implantacion:'grande',},
        {id:514,cantidad:'MUCHO',color:'ROJO',forma:'U',calvicie:'chica',implantacion:'chica',},
        {id:515,cantidad:'MUCHO',color:'ROJO',forma:'U',calvicie:'chica',implantacion:'mediana',},
        {id:516,cantidad:'MUCHO',color:'ROJO',forma:'U',calvicie:'chica',implantacion:'grande',},
        {id:517,cantidad:'MUCHO',color:'ROJO',forma:'U',calvicie:'mediana',implantacion:'chica',},
        {id:518,cantidad:'MUCHO',color:'ROJO',forma:'U',calvicie:'mediana',implantacion:'mediana',},
        {id:519,cantidad:'MUCHO',color:'ROJO',forma:'U',calvicie:'mediana',implantacion:'grande',},
        {id:520,cantidad:'MUCHO',color:'ROJO',forma:'U',calvicie:'grande',implantacion:'chica',},
        {id:521,cantidad:'MUCHO',color:'ROJO',forma:'U',calvicie:'grande',implantacion:'mediana',},
        {id:522,cantidad:'MUCHO',color:'ROJO',forma:'U',calvicie:'grande',implantacion:'grande',},
        {id:523,cantidad:'MUCHO',color:'ROJO',forma:'U invertida',calvicie:'chica',implantacion:'chica',},
        {id:524,cantidad:'MUCHO',color:'ROJO',forma:'U invertida',calvicie:'chica',implantacion:'mediana',},
        {id:525,cantidad:'MUCHO',color:'ROJO',forma:'U invertida',calvicie:'chica',implantacion:'grande',},
        {id:526,cantidad:'MUCHO',color:'ROJO',forma:'U invertida',calvicie:'mediana',implantacion:'chica',},
        {id:527,cantidad:'MUCHO',color:'ROJO',forma:'U invertida',calvicie:'mediana',implantacion:'mediana',},
        {id:528,cantidad:'MUCHO',color:'ROJO',forma:'U invertida',calvicie:'mediana',implantacion:'grande',},
        {id:529,cantidad:'MUCHO',color:'ROJO',forma:'U invertida',calvicie:'grande',implantacion:'chica',},
        {id:530,cantidad:'MUCHO',color:'ROJO',forma:'U invertida',calvicie:'grande',implantacion:'mediana',},
        {id:531,cantidad:'MUCHO',color:'ROJO',forma:'U invertida',calvicie:'grande',implantacion:'grande',},
        {id:532,cantidad:'MUCHO',color:'ROJO',forma:'Rapada',calvicie:'chica',implantacion:'chica',},
        {id:533,cantidad:'MUCHO',color:'ROJO',forma:'Rapada',calvicie:'chica',implantacion:'mediana',},
        {id:534,cantidad:'MUCHO',color:'ROJO',forma:'Rapada',calvicie:'chica',implantacion:'grande',},
        {id:535,cantidad:'MUCHO',color:'ROJO',forma:'Rapada',calvicie:'mediana',implantacion:'chica',},
        {id:536,cantidad:'MUCHO',color:'ROJO',forma:'Rapada',calvicie:'mediana',implantacion:'mediana',},
        {id:537,cantidad:'MUCHO',color:'ROJO',forma:'Rapada',calvicie:'mediana',implantacion:'grande',},
        {id:538,cantidad:'MUCHO',color:'ROJO',forma:'Rapada',calvicie:'grande',implantacion:'chica',},
        {id:539,cantidad:'MUCHO',color:'ROJO',forma:'Rapada',calvicie:'grande',implantacion:'mediana',},
        {id:540,cantidad:'MUCHO',color:'ROJO',forma:'Rapada',calvicie:'grande',implantacion:'grande',},
    ];
}
