export class arrCLASE_ARMA {
    public static readonly arreglo = [
        {id:1,claseArma:'fuego',tipo:'revolver',subtipo:'deportiva',},
        {id:2,claseArma:'fuego',tipo:'revolver',subtipo:'casa',},
        {id:3,claseArma:'fuego',tipo:'revolver',subtipo:'caza',},
        {id:4,claseArma:'fuego',tipo:'revolver',subtipo:'ultra ligero',},
        {id:5,claseArma:'fuego',tipo:'armas larga',subtipo:'deportiva',},
        {id:6,claseArma:'fuego',tipo:'armas larga',subtipo:'casa',},
        {id:7,claseArma:'fuego',tipo:'armas larga',subtipo:'caza',},
        {id:8,claseArma:'fuego',tipo:'armas larga',subtipo:'ultra ligero',},
        {id:9,claseArma:'fuego',tipo:'diabolo',subtipo:'deportiva',},
        {id:10,claseArma:'fuego',tipo:'diabolo',subtipo:'casa',},
        {id:11,claseArma:'fuego',tipo:'diabolo',subtipo:'caza',},
        {id:12,claseArma:'fuego',tipo:'diabolo',subtipo:'ultra ligero',},
        {id:13,claseArma:'fuego',tipo:'machetes',subtipo:'deportiva',},
        {id:14,claseArma:'fuego',tipo:'machetes',subtipo:'casa',},
        {id:15,claseArma:'fuego',tipo:'machetes',subtipo:'caza',},
        {id:16,claseArma:'fuego',tipo:'machetes',subtipo:'ultra ligero',},
        {id:17,claseArma:'blanca',tipo:'revolver',subtipo:'deportiva',},
        {id:18,claseArma:'blanca',tipo:'revolver',subtipo:'casa',},
        {id:19,claseArma:'blanca',tipo:'revolver',subtipo:'caza',},
        {id:20,claseArma:'blanca',tipo:'revolver',subtipo:'ultra ligero',},
        {id:21,claseArma:'blanca',tipo:'armas larga',subtipo:'deportiva',},
        {id:22,claseArma:'blanca',tipo:'armas larga',subtipo:'casa',},
        {id:23,claseArma:'blanca',tipo:'armas larga',subtipo:'caza',},
        {id:24,claseArma:'blanca',tipo:'armas larga',subtipo:'ultra ligero',},
        {id:25,claseArma:'blanca',tipo:'diabolo',subtipo:'deportiva',},
        {id:26,claseArma:'blanca',tipo:'diabolo',subtipo:'casa',},
        {id:27,claseArma:'blanca',tipo:'diabolo',subtipo:'caza',},
        {id:28,claseArma:'blanca',tipo:'diabolo',subtipo:'ultra ligero',},
        {id:29,claseArma:'blanca',tipo:'machetes',subtipo:'deportiva',},
        {id:30,claseArma:'blanca',tipo:'machetes',subtipo:'casa',},
        {id:31,claseArma:'blanca',tipo:'machetes',subtipo:'caza',},
        {id:32,claseArma:'blanca',tipo:'machetes',subtipo:'ultra ligero',},
        {id:33,claseArma:'aire',tipo:'revolver',subtipo:'deportiva',},
        {id:34,claseArma:'aire',tipo:'revolver',subtipo:'casa',},
        {id:35,claseArma:'aire',tipo:'revolver',subtipo:'caza',},
        {id:36,claseArma:'aire',tipo:'revolver',subtipo:'ultra ligero',},
        {id:37,claseArma:'aire',tipo:'armas larga',subtipo:'deportiva',},
        {id:38,claseArma:'aire',tipo:'armas larga',subtipo:'casa',},
        {id:39,claseArma:'aire',tipo:'armas larga',subtipo:'caza',},
        {id:40,claseArma:'aire',tipo:'armas larga',subtipo:'ultra ligero',},
        {id:41,claseArma:'aire',tipo:'diabolo',subtipo:'deportiva',},
        {id:42,claseArma:'aire',tipo:'diabolo',subtipo:'casa',},
        {id:43,claseArma:'aire',tipo:'diabolo',subtipo:'caza',},
        {id:44,claseArma:'aire',tipo:'diabolo',subtipo:'ultra ligero',},
        {id:45,claseArma:'aire',tipo:'machetes',subtipo:'deportiva',},
        {id:46,claseArma:'aire',tipo:'machetes',subtipo:'casa',},
        {id:47,claseArma:'aire',tipo:'machetes',subtipo:'caza',},
        {id:48,claseArma:'aire',tipo:'machetes',subtipo:'ultra ligero',},
    ];
}
