export class arrFRENTE_MENTON {
    public static readonly arreglo = [
        {id:1,alturaFrente:'1 DEDO',inclinacionFrente:'10 GRADOS',anchoFrente:'UNA CUARTA',tipoMenton:'FUERTE',inclinacionMenton:'10 GRADOS',},
        {id:2,alturaFrente:'1 DEDO',inclinacionFrente:'10 GRADOS',anchoFrente:'UNA CUARTA',tipoMenton:'FUERTE',inclinacionMenton:'20 GRADOS',},
        {id:3,alturaFrente:'1 DEDO',inclinacionFrente:'10 GRADOS',anchoFrente:'UNA CUARTA',tipoMenton:'FUERTE',inclinacionMenton:'MAS',},
        {id:4,alturaFrente:'1 DEDO',inclinacionFrente:'10 GRADOS',anchoFrente:'UNA CUARTA',tipoMenton:'DEVIL',inclinacionMenton:'10 GRADOS',},
        {id:5,alturaFrente:'1 DEDO',inclinacionFrente:'10 GRADOS',anchoFrente:'UNA CUARTA',tipoMenton:'DEVIL',inclinacionMenton:'20 GRADOS',},
        {id:6,alturaFrente:'1 DEDO',inclinacionFrente:'10 GRADOS',anchoFrente:'UNA CUARTA',tipoMenton:'DEVIL',inclinacionMenton:'MAS',},
        {id:7,alturaFrente:'1 DEDO',inclinacionFrente:'10 GRADOS',anchoFrente:'UN PIE',tipoMenton:'FUERTE',inclinacionMenton:'10 GRADOS',},
        {id:8,alturaFrente:'1 DEDO',inclinacionFrente:'10 GRADOS',anchoFrente:'UN PIE',tipoMenton:'FUERTE',inclinacionMenton:'20 GRADOS',},
        {id:9,alturaFrente:'1 DEDO',inclinacionFrente:'10 GRADOS',anchoFrente:'UN PIE',tipoMenton:'FUERTE',inclinacionMenton:'MAS',},
        {id:10,alturaFrente:'1 DEDO',inclinacionFrente:'10 GRADOS',anchoFrente:'UN PIE',tipoMenton:'DEVIL',inclinacionMenton:'10 GRADOS',},
        {id:11,alturaFrente:'1 DEDO',inclinacionFrente:'10 GRADOS',anchoFrente:'UN PIE',tipoMenton:'DEVIL',inclinacionMenton:'20 GRADOS',},
        {id:12,alturaFrente:'1 DEDO',inclinacionFrente:'10 GRADOS',anchoFrente:'UN PIE',tipoMenton:'DEVIL',inclinacionMenton:'MAS',},
        {id:13,alturaFrente:'1 DEDO',inclinacionFrente:'10 GRADOS',anchoFrente:'MAS',tipoMenton:'FUERTE',inclinacionMenton:'10 GRADOS',},
        {id:14,alturaFrente:'1 DEDO',inclinacionFrente:'10 GRADOS',anchoFrente:'MAS',tipoMenton:'FUERTE',inclinacionMenton:'20 GRADOS',},
        {id:15,alturaFrente:'1 DEDO',inclinacionFrente:'10 GRADOS',anchoFrente:'MAS',tipoMenton:'FUERTE',inclinacionMenton:'MAS',},
        {id:16,alturaFrente:'1 DEDO',inclinacionFrente:'10 GRADOS',anchoFrente:'MAS',tipoMenton:'DEVIL',inclinacionMenton:'10 GRADOS',},
        {id:17,alturaFrente:'1 DEDO',inclinacionFrente:'10 GRADOS',anchoFrente:'MAS',tipoMenton:'DEVIL',inclinacionMenton:'20 GRADOS',},
        {id:18,alturaFrente:'1 DEDO',inclinacionFrente:'10 GRADOS',anchoFrente:'MAS',tipoMenton:'DEVIL',inclinacionMenton:'MAS',},
        {id:19,alturaFrente:'1 DEDO',inclinacionFrente:'20 GRADOS',anchoFrente:'UNA CUARTA',tipoMenton:'FUERTE',inclinacionMenton:'10 GRADOS',},
        {id:20,alturaFrente:'1 DEDO',inclinacionFrente:'20 GRADOS',anchoFrente:'UNA CUARTA',tipoMenton:'FUERTE',inclinacionMenton:'20 GRADOS',},
        {id:21,alturaFrente:'1 DEDO',inclinacionFrente:'20 GRADOS',anchoFrente:'UNA CUARTA',tipoMenton:'FUERTE',inclinacionMenton:'MAS',},
        {id:22,alturaFrente:'1 DEDO',inclinacionFrente:'20 GRADOS',anchoFrente:'UNA CUARTA',tipoMenton:'DEVIL',inclinacionMenton:'10 GRADOS',},
        {id:23,alturaFrente:'1 DEDO',inclinacionFrente:'20 GRADOS',anchoFrente:'UNA CUARTA',tipoMenton:'DEVIL',inclinacionMenton:'20 GRADOS',},
        {id:24,alturaFrente:'1 DEDO',inclinacionFrente:'20 GRADOS',anchoFrente:'UNA CUARTA',tipoMenton:'DEVIL',inclinacionMenton:'MAS',},
        {id:25,alturaFrente:'1 DEDO',inclinacionFrente:'20 GRADOS',anchoFrente:'UN PIE',tipoMenton:'FUERTE',inclinacionMenton:'10 GRADOS',},
        {id:26,alturaFrente:'1 DEDO',inclinacionFrente:'20 GRADOS',anchoFrente:'UN PIE',tipoMenton:'FUERTE',inclinacionMenton:'20 GRADOS',},
        {id:27,alturaFrente:'1 DEDO',inclinacionFrente:'20 GRADOS',anchoFrente:'UN PIE',tipoMenton:'FUERTE',inclinacionMenton:'MAS',},
        {id:28,alturaFrente:'1 DEDO',inclinacionFrente:'20 GRADOS',anchoFrente:'UN PIE',tipoMenton:'DEVIL',inclinacionMenton:'10 GRADOS',},
        {id:29,alturaFrente:'1 DEDO',inclinacionFrente:'20 GRADOS',anchoFrente:'UN PIE',tipoMenton:'DEVIL',inclinacionMenton:'20 GRADOS',},
        {id:30,alturaFrente:'1 DEDO',inclinacionFrente:'20 GRADOS',anchoFrente:'UN PIE',tipoMenton:'DEVIL',inclinacionMenton:'MAS',},
        {id:31,alturaFrente:'1 DEDO',inclinacionFrente:'20 GRADOS',anchoFrente:'MAS',tipoMenton:'FUERTE',inclinacionMenton:'10 GRADOS',},
        {id:32,alturaFrente:'1 DEDO',inclinacionFrente:'20 GRADOS',anchoFrente:'MAS',tipoMenton:'FUERTE',inclinacionMenton:'20 GRADOS',},
        {id:33,alturaFrente:'1 DEDO',inclinacionFrente:'20 GRADOS',anchoFrente:'MAS',tipoMenton:'FUERTE',inclinacionMenton:'MAS',},
        {id:34,alturaFrente:'1 DEDO',inclinacionFrente:'20 GRADOS',anchoFrente:'MAS',tipoMenton:'DEVIL',inclinacionMenton:'10 GRADOS',},
        {id:35,alturaFrente:'1 DEDO',inclinacionFrente:'20 GRADOS',anchoFrente:'MAS',tipoMenton:'DEVIL',inclinacionMenton:'20 GRADOS',},
        {id:36,alturaFrente:'1 DEDO',inclinacionFrente:'20 GRADOS',anchoFrente:'MAS',tipoMenton:'DEVIL',inclinacionMenton:'MAS',},
        {id:37,alturaFrente:'1 DEDO',inclinacionFrente:'MAS',anchoFrente:'UNA CUARTA',tipoMenton:'FUERTE',inclinacionMenton:'10 GRADOS',},
        {id:38,alturaFrente:'1 DEDO',inclinacionFrente:'MAS',anchoFrente:'UNA CUARTA',tipoMenton:'FUERTE',inclinacionMenton:'20 GRADOS',},
        {id:39,alturaFrente:'1 DEDO',inclinacionFrente:'MAS',anchoFrente:'UNA CUARTA',tipoMenton:'FUERTE',inclinacionMenton:'MAS',},
        {id:40,alturaFrente:'1 DEDO',inclinacionFrente:'MAS',anchoFrente:'UNA CUARTA',tipoMenton:'DEVIL',inclinacionMenton:'10 GRADOS',},
        {id:41,alturaFrente:'1 DEDO',inclinacionFrente:'MAS',anchoFrente:'UNA CUARTA',tipoMenton:'DEVIL',inclinacionMenton:'20 GRADOS',},
        {id:42,alturaFrente:'1 DEDO',inclinacionFrente:'MAS',anchoFrente:'UNA CUARTA',tipoMenton:'DEVIL',inclinacionMenton:'MAS',},
        {id:43,alturaFrente:'1 DEDO',inclinacionFrente:'MAS',anchoFrente:'UN PIE',tipoMenton:'FUERTE',inclinacionMenton:'10 GRADOS',},
        {id:44,alturaFrente:'1 DEDO',inclinacionFrente:'MAS',anchoFrente:'UN PIE',tipoMenton:'FUERTE',inclinacionMenton:'20 GRADOS',},
        {id:45,alturaFrente:'1 DEDO',inclinacionFrente:'MAS',anchoFrente:'UN PIE',tipoMenton:'FUERTE',inclinacionMenton:'MAS',},
        {id:46,alturaFrente:'1 DEDO',inclinacionFrente:'MAS',anchoFrente:'UN PIE',tipoMenton:'DEVIL',inclinacionMenton:'10 GRADOS',},
        {id:47,alturaFrente:'1 DEDO',inclinacionFrente:'MAS',anchoFrente:'UN PIE',tipoMenton:'DEVIL',inclinacionMenton:'20 GRADOS',},
        {id:48,alturaFrente:'1 DEDO',inclinacionFrente:'MAS',anchoFrente:'UN PIE',tipoMenton:'DEVIL',inclinacionMenton:'MAS',},
        {id:49,alturaFrente:'1 DEDO',inclinacionFrente:'MAS',anchoFrente:'MAS',tipoMenton:'FUERTE',inclinacionMenton:'10 GRADOS',},
        {id:50,alturaFrente:'1 DEDO',inclinacionFrente:'MAS',anchoFrente:'MAS',tipoMenton:'FUERTE',inclinacionMenton:'20 GRADOS',},
        {id:51,alturaFrente:'1 DEDO',inclinacionFrente:'MAS',anchoFrente:'MAS',tipoMenton:'FUERTE',inclinacionMenton:'MAS',},
        {id:52,alturaFrente:'1 DEDO',inclinacionFrente:'MAS',anchoFrente:'MAS',tipoMenton:'DEVIL',inclinacionMenton:'10 GRADOS',},
        {id:53,alturaFrente:'1 DEDO',inclinacionFrente:'MAS',anchoFrente:'MAS',tipoMenton:'DEVIL',inclinacionMenton:'20 GRADOS',},
        {id:54,alturaFrente:'1 DEDO',inclinacionFrente:'MAS',anchoFrente:'MAS',tipoMenton:'DEVIL',inclinacionMenton:'MAS',},
        {id:55,alturaFrente:'2 DEDOS',inclinacionFrente:'10 GRADOS',anchoFrente:'UNA CUARTA',tipoMenton:'FUERTE',inclinacionMenton:'10 GRADOS',},
        {id:56,alturaFrente:'2 DEDOS',inclinacionFrente:'10 GRADOS',anchoFrente:'UNA CUARTA',tipoMenton:'FUERTE',inclinacionMenton:'20 GRADOS',},
        {id:57,alturaFrente:'2 DEDOS',inclinacionFrente:'10 GRADOS',anchoFrente:'UNA CUARTA',tipoMenton:'FUERTE',inclinacionMenton:'MAS',},
        {id:58,alturaFrente:'2 DEDOS',inclinacionFrente:'10 GRADOS',anchoFrente:'UNA CUARTA',tipoMenton:'DEVIL',inclinacionMenton:'10 GRADOS',},
        {id:59,alturaFrente:'2 DEDOS',inclinacionFrente:'10 GRADOS',anchoFrente:'UNA CUARTA',tipoMenton:'DEVIL',inclinacionMenton:'20 GRADOS',},
        {id:60,alturaFrente:'2 DEDOS',inclinacionFrente:'10 GRADOS',anchoFrente:'UNA CUARTA',tipoMenton:'DEVIL',inclinacionMenton:'MAS',},
        {id:61,alturaFrente:'2 DEDOS',inclinacionFrente:'10 GRADOS',anchoFrente:'UN PIE',tipoMenton:'FUERTE',inclinacionMenton:'10 GRADOS',},
        {id:62,alturaFrente:'2 DEDOS',inclinacionFrente:'10 GRADOS',anchoFrente:'UN PIE',tipoMenton:'FUERTE',inclinacionMenton:'20 GRADOS',},
        {id:63,alturaFrente:'2 DEDOS',inclinacionFrente:'10 GRADOS',anchoFrente:'UN PIE',tipoMenton:'FUERTE',inclinacionMenton:'MAS',},
        {id:64,alturaFrente:'2 DEDOS',inclinacionFrente:'10 GRADOS',anchoFrente:'UN PIE',tipoMenton:'DEVIL',inclinacionMenton:'10 GRADOS',},
        {id:65,alturaFrente:'2 DEDOS',inclinacionFrente:'10 GRADOS',anchoFrente:'UN PIE',tipoMenton:'DEVIL',inclinacionMenton:'20 GRADOS',},
        {id:66,alturaFrente:'2 DEDOS',inclinacionFrente:'10 GRADOS',anchoFrente:'UN PIE',tipoMenton:'DEVIL',inclinacionMenton:'MAS',},
        {id:67,alturaFrente:'2 DEDOS',inclinacionFrente:'10 GRADOS',anchoFrente:'MAS',tipoMenton:'FUERTE',inclinacionMenton:'10 GRADOS',},
        {id:68,alturaFrente:'2 DEDOS',inclinacionFrente:'10 GRADOS',anchoFrente:'MAS',tipoMenton:'FUERTE',inclinacionMenton:'20 GRADOS',},
        {id:69,alturaFrente:'2 DEDOS',inclinacionFrente:'10 GRADOS',anchoFrente:'MAS',tipoMenton:'FUERTE',inclinacionMenton:'MAS',},
        {id:70,alturaFrente:'2 DEDOS',inclinacionFrente:'10 GRADOS',anchoFrente:'MAS',tipoMenton:'DEVIL',inclinacionMenton:'10 GRADOS',},
        {id:71,alturaFrente:'2 DEDOS',inclinacionFrente:'10 GRADOS',anchoFrente:'MAS',tipoMenton:'DEVIL',inclinacionMenton:'20 GRADOS',},
        {id:72,alturaFrente:'2 DEDOS',inclinacionFrente:'10 GRADOS',anchoFrente:'MAS',tipoMenton:'DEVIL',inclinacionMenton:'MAS',},
        {id:73,alturaFrente:'2 DEDOS',inclinacionFrente:'20 GRADOS',anchoFrente:'UNA CUARTA',tipoMenton:'FUERTE',inclinacionMenton:'10 GRADOS',},
        {id:74,alturaFrente:'2 DEDOS',inclinacionFrente:'20 GRADOS',anchoFrente:'UNA CUARTA',tipoMenton:'FUERTE',inclinacionMenton:'20 GRADOS',},
        {id:75,alturaFrente:'2 DEDOS',inclinacionFrente:'20 GRADOS',anchoFrente:'UNA CUARTA',tipoMenton:'FUERTE',inclinacionMenton:'MAS',},
        {id:76,alturaFrente:'2 DEDOS',inclinacionFrente:'20 GRADOS',anchoFrente:'UNA CUARTA',tipoMenton:'DEVIL',inclinacionMenton:'10 GRADOS',},
        {id:77,alturaFrente:'2 DEDOS',inclinacionFrente:'20 GRADOS',anchoFrente:'UNA CUARTA',tipoMenton:'DEVIL',inclinacionMenton:'20 GRADOS',},
        {id:78,alturaFrente:'2 DEDOS',inclinacionFrente:'20 GRADOS',anchoFrente:'UNA CUARTA',tipoMenton:'DEVIL',inclinacionMenton:'MAS',},
        {id:79,alturaFrente:'2 DEDOS',inclinacionFrente:'20 GRADOS',anchoFrente:'UN PIE',tipoMenton:'FUERTE',inclinacionMenton:'10 GRADOS',},
        {id:80,alturaFrente:'2 DEDOS',inclinacionFrente:'20 GRADOS',anchoFrente:'UN PIE',tipoMenton:'FUERTE',inclinacionMenton:'20 GRADOS',},
        {id:81,alturaFrente:'2 DEDOS',inclinacionFrente:'20 GRADOS',anchoFrente:'UN PIE',tipoMenton:'FUERTE',inclinacionMenton:'MAS',},
        {id:82,alturaFrente:'2 DEDOS',inclinacionFrente:'20 GRADOS',anchoFrente:'UN PIE',tipoMenton:'DEVIL',inclinacionMenton:'10 GRADOS',},
        {id:83,alturaFrente:'2 DEDOS',inclinacionFrente:'20 GRADOS',anchoFrente:'UN PIE',tipoMenton:'DEVIL',inclinacionMenton:'20 GRADOS',},
        {id:84,alturaFrente:'2 DEDOS',inclinacionFrente:'20 GRADOS',anchoFrente:'UN PIE',tipoMenton:'DEVIL',inclinacionMenton:'MAS',},
        {id:85,alturaFrente:'2 DEDOS',inclinacionFrente:'20 GRADOS',anchoFrente:'MAS',tipoMenton:'FUERTE',inclinacionMenton:'10 GRADOS',},
        {id:86,alturaFrente:'2 DEDOS',inclinacionFrente:'20 GRADOS',anchoFrente:'MAS',tipoMenton:'FUERTE',inclinacionMenton:'20 GRADOS',},
        {id:87,alturaFrente:'2 DEDOS',inclinacionFrente:'20 GRADOS',anchoFrente:'MAS',tipoMenton:'FUERTE',inclinacionMenton:'MAS',},
        {id:88,alturaFrente:'2 DEDOS',inclinacionFrente:'20 GRADOS',anchoFrente:'MAS',tipoMenton:'DEVIL',inclinacionMenton:'10 GRADOS',},
        {id:89,alturaFrente:'2 DEDOS',inclinacionFrente:'20 GRADOS',anchoFrente:'MAS',tipoMenton:'DEVIL',inclinacionMenton:'20 GRADOS',},
        {id:90,alturaFrente:'2 DEDOS',inclinacionFrente:'20 GRADOS',anchoFrente:'MAS',tipoMenton:'DEVIL',inclinacionMenton:'MAS',},
        {id:91,alturaFrente:'2 DEDOS',inclinacionFrente:'MAS',anchoFrente:'UNA CUARTA',tipoMenton:'FUERTE',inclinacionMenton:'10 GRADOS',},
        {id:92,alturaFrente:'2 DEDOS',inclinacionFrente:'MAS',anchoFrente:'UNA CUARTA',tipoMenton:'FUERTE',inclinacionMenton:'20 GRADOS',},
        {id:93,alturaFrente:'2 DEDOS',inclinacionFrente:'MAS',anchoFrente:'UNA CUARTA',tipoMenton:'FUERTE',inclinacionMenton:'MAS',},
        {id:94,alturaFrente:'2 DEDOS',inclinacionFrente:'MAS',anchoFrente:'UNA CUARTA',tipoMenton:'DEVIL',inclinacionMenton:'10 GRADOS',},
        {id:95,alturaFrente:'2 DEDOS',inclinacionFrente:'MAS',anchoFrente:'UNA CUARTA',tipoMenton:'DEVIL',inclinacionMenton:'20 GRADOS',},
        {id:96,alturaFrente:'2 DEDOS',inclinacionFrente:'MAS',anchoFrente:'UNA CUARTA',tipoMenton:'DEVIL',inclinacionMenton:'MAS',},
        {id:97,alturaFrente:'2 DEDOS',inclinacionFrente:'MAS',anchoFrente:'UN PIE',tipoMenton:'FUERTE',inclinacionMenton:'10 GRADOS',},
        {id:98,alturaFrente:'2 DEDOS',inclinacionFrente:'MAS',anchoFrente:'UN PIE',tipoMenton:'FUERTE',inclinacionMenton:'20 GRADOS',},
        {id:99,alturaFrente:'2 DEDOS',inclinacionFrente:'MAS',anchoFrente:'UN PIE',tipoMenton:'FUERTE',inclinacionMenton:'MAS',},
        {id:100,alturaFrente:'2 DEDOS',inclinacionFrente:'MAS',anchoFrente:'UN PIE',tipoMenton:'DEVIL',inclinacionMenton:'10 GRADOS',},
        {id:101,alturaFrente:'2 DEDOS',inclinacionFrente:'MAS',anchoFrente:'UN PIE',tipoMenton:'DEVIL',inclinacionMenton:'20 GRADOS',},
        {id:102,alturaFrente:'2 DEDOS',inclinacionFrente:'MAS',anchoFrente:'UN PIE',tipoMenton:'DEVIL',inclinacionMenton:'MAS',},
        {id:103,alturaFrente:'2 DEDOS',inclinacionFrente:'MAS',anchoFrente:'MAS',tipoMenton:'FUERTE',inclinacionMenton:'10 GRADOS',},
        {id:104,alturaFrente:'2 DEDOS',inclinacionFrente:'MAS',anchoFrente:'MAS',tipoMenton:'FUERTE',inclinacionMenton:'20 GRADOS',},
        {id:105,alturaFrente:'2 DEDOS',inclinacionFrente:'MAS',anchoFrente:'MAS',tipoMenton:'FUERTE',inclinacionMenton:'MAS',},
        {id:106,alturaFrente:'2 DEDOS',inclinacionFrente:'MAS',anchoFrente:'MAS',tipoMenton:'DEVIL',inclinacionMenton:'10 GRADOS',},
        {id:107,alturaFrente:'2 DEDOS',inclinacionFrente:'MAS',anchoFrente:'MAS',tipoMenton:'DEVIL',inclinacionMenton:'20 GRADOS',},
        {id:108,alturaFrente:'2 DEDOS',inclinacionFrente:'MAS',anchoFrente:'MAS',tipoMenton:'DEVIL',inclinacionMenton:'MAS',},
        {id:109,alturaFrente:'3 DEDOS',inclinacionFrente:'10 GRADOS',anchoFrente:'UNA CUARTA',tipoMenton:'FUERTE',inclinacionMenton:'10 GRADOS',},
        {id:110,alturaFrente:'3 DEDOS',inclinacionFrente:'10 GRADOS',anchoFrente:'UNA CUARTA',tipoMenton:'FUERTE',inclinacionMenton:'20 GRADOS',},
        {id:111,alturaFrente:'3 DEDOS',inclinacionFrente:'10 GRADOS',anchoFrente:'UNA CUARTA',tipoMenton:'FUERTE',inclinacionMenton:'MAS',},
        {id:112,alturaFrente:'3 DEDOS',inclinacionFrente:'10 GRADOS',anchoFrente:'UNA CUARTA',tipoMenton:'DEVIL',inclinacionMenton:'10 GRADOS',},
        {id:113,alturaFrente:'3 DEDOS',inclinacionFrente:'10 GRADOS',anchoFrente:'UNA CUARTA',tipoMenton:'DEVIL',inclinacionMenton:'20 GRADOS',},
        {id:114,alturaFrente:'3 DEDOS',inclinacionFrente:'10 GRADOS',anchoFrente:'UNA CUARTA',tipoMenton:'DEVIL',inclinacionMenton:'MAS',},
        {id:115,alturaFrente:'3 DEDOS',inclinacionFrente:'10 GRADOS',anchoFrente:'UN PIE',tipoMenton:'FUERTE',inclinacionMenton:'10 GRADOS',},
        {id:116,alturaFrente:'3 DEDOS',inclinacionFrente:'10 GRADOS',anchoFrente:'UN PIE',tipoMenton:'FUERTE',inclinacionMenton:'20 GRADOS',},
        {id:117,alturaFrente:'3 DEDOS',inclinacionFrente:'10 GRADOS',anchoFrente:'UN PIE',tipoMenton:'FUERTE',inclinacionMenton:'MAS',},
        {id:118,alturaFrente:'3 DEDOS',inclinacionFrente:'10 GRADOS',anchoFrente:'UN PIE',tipoMenton:'DEVIL',inclinacionMenton:'10 GRADOS',},
        {id:119,alturaFrente:'3 DEDOS',inclinacionFrente:'10 GRADOS',anchoFrente:'UN PIE',tipoMenton:'DEVIL',inclinacionMenton:'20 GRADOS',},
        {id:120,alturaFrente:'3 DEDOS',inclinacionFrente:'10 GRADOS',anchoFrente:'UN PIE',tipoMenton:'DEVIL',inclinacionMenton:'MAS',},
        {id:121,alturaFrente:'3 DEDOS',inclinacionFrente:'10 GRADOS',anchoFrente:'MAS',tipoMenton:'FUERTE',inclinacionMenton:'10 GRADOS',},
        {id:122,alturaFrente:'3 DEDOS',inclinacionFrente:'10 GRADOS',anchoFrente:'MAS',tipoMenton:'FUERTE',inclinacionMenton:'20 GRADOS',},
        {id:123,alturaFrente:'3 DEDOS',inclinacionFrente:'10 GRADOS',anchoFrente:'MAS',tipoMenton:'FUERTE',inclinacionMenton:'MAS',},
        {id:124,alturaFrente:'3 DEDOS',inclinacionFrente:'10 GRADOS',anchoFrente:'MAS',tipoMenton:'DEVIL',inclinacionMenton:'10 GRADOS',},
        {id:125,alturaFrente:'3 DEDOS',inclinacionFrente:'10 GRADOS',anchoFrente:'MAS',tipoMenton:'DEVIL',inclinacionMenton:'20 GRADOS',},
        {id:126,alturaFrente:'3 DEDOS',inclinacionFrente:'10 GRADOS',anchoFrente:'MAS',tipoMenton:'DEVIL',inclinacionMenton:'MAS',},
        {id:127,alturaFrente:'3 DEDOS',inclinacionFrente:'20 GRADOS',anchoFrente:'UNA CUARTA',tipoMenton:'FUERTE',inclinacionMenton:'10 GRADOS',},
        {id:128,alturaFrente:'3 DEDOS',inclinacionFrente:'20 GRADOS',anchoFrente:'UNA CUARTA',tipoMenton:'FUERTE',inclinacionMenton:'20 GRADOS',},
        {id:129,alturaFrente:'3 DEDOS',inclinacionFrente:'20 GRADOS',anchoFrente:'UNA CUARTA',tipoMenton:'FUERTE',inclinacionMenton:'MAS',},
        {id:130,alturaFrente:'3 DEDOS',inclinacionFrente:'20 GRADOS',anchoFrente:'UNA CUARTA',tipoMenton:'DEVIL',inclinacionMenton:'10 GRADOS',},
        {id:131,alturaFrente:'3 DEDOS',inclinacionFrente:'20 GRADOS',anchoFrente:'UNA CUARTA',tipoMenton:'DEVIL',inclinacionMenton:'20 GRADOS',},
        {id:132,alturaFrente:'3 DEDOS',inclinacionFrente:'20 GRADOS',anchoFrente:'UNA CUARTA',tipoMenton:'DEVIL',inclinacionMenton:'MAS',},
        {id:133,alturaFrente:'3 DEDOS',inclinacionFrente:'20 GRADOS',anchoFrente:'UN PIE',tipoMenton:'FUERTE',inclinacionMenton:'10 GRADOS',},
        {id:134,alturaFrente:'3 DEDOS',inclinacionFrente:'20 GRADOS',anchoFrente:'UN PIE',tipoMenton:'FUERTE',inclinacionMenton:'20 GRADOS',},
        {id:135,alturaFrente:'3 DEDOS',inclinacionFrente:'20 GRADOS',anchoFrente:'UN PIE',tipoMenton:'FUERTE',inclinacionMenton:'MAS',},
        {id:136,alturaFrente:'3 DEDOS',inclinacionFrente:'20 GRADOS',anchoFrente:'UN PIE',tipoMenton:'DEVIL',inclinacionMenton:'10 GRADOS',},
        {id:137,alturaFrente:'3 DEDOS',inclinacionFrente:'20 GRADOS',anchoFrente:'UN PIE',tipoMenton:'DEVIL',inclinacionMenton:'20 GRADOS',},
        {id:138,alturaFrente:'3 DEDOS',inclinacionFrente:'20 GRADOS',anchoFrente:'UN PIE',tipoMenton:'DEVIL',inclinacionMenton:'MAS',},
        {id:139,alturaFrente:'3 DEDOS',inclinacionFrente:'20 GRADOS',anchoFrente:'MAS',tipoMenton:'FUERTE',inclinacionMenton:'10 GRADOS',},
        {id:140,alturaFrente:'3 DEDOS',inclinacionFrente:'20 GRADOS',anchoFrente:'MAS',tipoMenton:'FUERTE',inclinacionMenton:'20 GRADOS',},
        {id:141,alturaFrente:'3 DEDOS',inclinacionFrente:'20 GRADOS',anchoFrente:'MAS',tipoMenton:'FUERTE',inclinacionMenton:'MAS',},
        {id:142,alturaFrente:'3 DEDOS',inclinacionFrente:'20 GRADOS',anchoFrente:'MAS',tipoMenton:'DEVIL',inclinacionMenton:'10 GRADOS',},
        {id:143,alturaFrente:'3 DEDOS',inclinacionFrente:'20 GRADOS',anchoFrente:'MAS',tipoMenton:'DEVIL',inclinacionMenton:'20 GRADOS',},
        {id:144,alturaFrente:'3 DEDOS',inclinacionFrente:'20 GRADOS',anchoFrente:'MAS',tipoMenton:'DEVIL',inclinacionMenton:'MAS',},
        {id:145,alturaFrente:'3 DEDOS',inclinacionFrente:'MAS',anchoFrente:'UNA CUARTA',tipoMenton:'FUERTE',inclinacionMenton:'10 GRADOS',},
        {id:146,alturaFrente:'3 DEDOS',inclinacionFrente:'MAS',anchoFrente:'UNA CUARTA',tipoMenton:'FUERTE',inclinacionMenton:'20 GRADOS',},
        {id:147,alturaFrente:'3 DEDOS',inclinacionFrente:'MAS',anchoFrente:'UNA CUARTA',tipoMenton:'FUERTE',inclinacionMenton:'MAS',},
        {id:148,alturaFrente:'3 DEDOS',inclinacionFrente:'MAS',anchoFrente:'UNA CUARTA',tipoMenton:'DEVIL',inclinacionMenton:'10 GRADOS',},
        {id:149,alturaFrente:'3 DEDOS',inclinacionFrente:'MAS',anchoFrente:'UNA CUARTA',tipoMenton:'DEVIL',inclinacionMenton:'20 GRADOS',},
        {id:150,alturaFrente:'3 DEDOS',inclinacionFrente:'MAS',anchoFrente:'UNA CUARTA',tipoMenton:'DEVIL',inclinacionMenton:'MAS',},
        {id:151,alturaFrente:'3 DEDOS',inclinacionFrente:'MAS',anchoFrente:'UN PIE',tipoMenton:'FUERTE',inclinacionMenton:'10 GRADOS',},
        {id:152,alturaFrente:'3 DEDOS',inclinacionFrente:'MAS',anchoFrente:'UN PIE',tipoMenton:'FUERTE',inclinacionMenton:'20 GRADOS',},
        {id:153,alturaFrente:'3 DEDOS',inclinacionFrente:'MAS',anchoFrente:'UN PIE',tipoMenton:'FUERTE',inclinacionMenton:'MAS',},
        {id:154,alturaFrente:'3 DEDOS',inclinacionFrente:'MAS',anchoFrente:'UN PIE',tipoMenton:'DEVIL',inclinacionMenton:'10 GRADOS',},
        {id:155,alturaFrente:'3 DEDOS',inclinacionFrente:'MAS',anchoFrente:'UN PIE',tipoMenton:'DEVIL',inclinacionMenton:'20 GRADOS',},
        {id:156,alturaFrente:'3 DEDOS',inclinacionFrente:'MAS',anchoFrente:'UN PIE',tipoMenton:'DEVIL',inclinacionMenton:'MAS',},
        {id:157,alturaFrente:'3 DEDOS',inclinacionFrente:'MAS',anchoFrente:'MAS',tipoMenton:'FUERTE',inclinacionMenton:'10 GRADOS',},
        {id:158,alturaFrente:'3 DEDOS',inclinacionFrente:'MAS',anchoFrente:'MAS',tipoMenton:'FUERTE',inclinacionMenton:'20 GRADOS',},
        {id:159,alturaFrente:'3 DEDOS',inclinacionFrente:'MAS',anchoFrente:'MAS',tipoMenton:'FUERTE',inclinacionMenton:'MAS',},
        {id:160,alturaFrente:'3 DEDOS',inclinacionFrente:'MAS',anchoFrente:'MAS',tipoMenton:'DEVIL',inclinacionMenton:'10 GRADOS',},
        {id:161,alturaFrente:'3 DEDOS',inclinacionFrente:'MAS',anchoFrente:'MAS',tipoMenton:'DEVIL',inclinacionMenton:'20 GRADOS',},
        {id:162,alturaFrente:'3 DEDOS',inclinacionFrente:'MAS',anchoFrente:'MAS',tipoMenton:'DEVIL',inclinacionMenton:'MAS',},
    ];
}
