export class arrMOTIVO_REGISTRO_COLOR_CLASE {
    public static readonly arreglo = [
        {id:1,motivoRegistro:'por obligacion',clase:'patito',color:'azul',},
        {id:2,motivoRegistro:'por obligacion',clase:'patito',color:'rojo',},
        {id:3,motivoRegistro:'por obligacion',clase:'patito',color:'verde',},
        {id:4,motivoRegistro:'por obligacion',clase:'patito',color:'blanco',},
        {id:5,motivoRegistro:'por obligacion',clase:'patito',color:'negro',},
        {id:6,motivoRegistro:'por obligacion',clase:'pato',color:'azul',},
        {id:7,motivoRegistro:'por obligacion',clase:'pato',color:'rojo',},
        {id:8,motivoRegistro:'por obligacion',clase:'pato',color:'verde',},
        {id:9,motivoRegistro:'por obligacion',clase:'pato',color:'blanco',},
        {id:10,motivoRegistro:'por obligacion',clase:'pato',color:'negro',},
        {id:11,motivoRegistro:'por obligacion',clase:'mcqua',color:'azul',},
        {id:12,motivoRegistro:'por obligacion',clase:'mcqua',color:'rojo',},
        {id:13,motivoRegistro:'por obligacion',clase:'mcqua',color:'verde',},
        {id:14,motivoRegistro:'por obligacion',clase:'mcqua',color:'blanco',},
        {id:15,motivoRegistro:'por obligacion',clase:'mcqua',color:'negro',},
        {id:16,motivoRegistro:'por que si',clase:'patito',color:'azul',},
        {id:17,motivoRegistro:'por que si',clase:'patito',color:'rojo',},
        {id:18,motivoRegistro:'por que si',clase:'patito',color:'verde',},
        {id:19,motivoRegistro:'por que si',clase:'patito',color:'blanco',},
        {id:20,motivoRegistro:'por que si',clase:'patito',color:'negro',},
        {id:21,motivoRegistro:'por que si',clase:'pato',color:'azul',},
        {id:22,motivoRegistro:'por que si',clase:'pato',color:'rojo',},
        {id:23,motivoRegistro:'por que si',clase:'pato',color:'verde',},
        {id:24,motivoRegistro:'por que si',clase:'pato',color:'blanco',},
        {id:25,motivoRegistro:'por que si',clase:'pato',color:'negro',},
        {id:26,motivoRegistro:'por que si',clase:'mcqua',color:'azul',},
        {id:27,motivoRegistro:'por que si',clase:'mcqua',color:'rojo',},
        {id:28,motivoRegistro:'por que si',clase:'mcqua',color:'verde',},
        {id:29,motivoRegistro:'por que si',clase:'mcqua',color:'blanco',},
        {id:30,motivoRegistro:'por que si',clase:'mcqua',color:'negro',},
    ];
}
